src/objects/CMSComponent__c.object
<CustomObject>
    <fields>
        <fullName>FieldSet__c</fullName>
        <label>FieldSet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <defaultValue>6</defaultValue>
        <inlineHelpText>Set the number of items to show per page</inlineHelpText>
        <label>Items per Page</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderBy__c</fullName>
        <description>Used on the Catalogo Component to give to the user the option to order the rewards</description>
        <label>Order By</label>
        <picklist>
            <picklistValues>
                <fullName>Name ASC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>List</fullName>
        <active>true</active>
        <description>Record type for component Transactions, Redemptions, Organization Members, Member Selecction, Branches, Badges</description>
        <label>List</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>    
</CustomObject>

src/objects/FieloAlpha__Program__c.object
<CustomObject>
    <description>Settings of each of your Fielo programs. You can create up to XXXX different programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BadgeAPI.cls
public with sharing class BadgeAPI implements CMSDataInterface{
	
	//BADGES
    public Map<Id, Object> getBulkData(List<CMSComponent__c> components){
        FieloAlpha__Program__c program = FieloAlpha.ProgramUtil.getProgramByDomain();
        Map<Id,Object> newMapData = new Map<Id,Object>();
        //Prepare all the queries
        for(Component__c c : components){
            if(c.Limit__c == null)
                c.Limit__c = 5;
            
            newMapData.put(c.Id, getBadges(OrganizationUtil.getFieldSet(c.FieldSet__c), program.Id, c.Limit__c.intValue(), 0, c.OrderBy__c));
        }
    }

    public List<sObject> getData(Component__c component, Integer pageNumber, String orderBy, String filters){        
        FieloAlpha__Program__c program = FieloAlpha.ProgramUtil.getProgramByDomain();
        //Prepare all the queries        
        if(component.Limit__c == null)
            component.Limit__c = 5;

        //Calculate the offset from the Page Number
        Integer offset = Integer.valueOf(component.Limit__c * (pageNumber - 1));
        return getBadges(OrganizationUtil.getFieldSet(component.FieldSet__c), program.Id, Integer.valueOf(component.Limit__c), offset, orderBy);        
    }

}