src/objects/FieloPLT__Badge__c.object
<CustomObject>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__BadgeMember__c.object
<CustomObject>
    <description>Badges obtained by each Member.</description>
    <fields>
        <fullName>FieloPLT__Badge__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Badge granted to a Member.</description>
        <inlineHelpText>Badge granted to a Member.</inlineHelpText>
        <label>Badge</label>
        <referenceTo>FieloPLT__Badge__c</referenceTo>
        <relationshipLabel>Badge Members</relationshipLabel>
        <relationshipName>BadgesMembers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Member who obtained a Badge.</description>
        <inlineHelpText>Member who obtained a Badge.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Badge Members</relationshipLabel>
        <relationshipName>BadgesMembers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Badge Member</label>
    <nameField>
        <label>BadgeMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_BadgeService.cls
public with sharing class FieloCMSPLT_BadgeService{
	
    public static List<FieloPLT__Badge__c> getBadges(Set<String> fields, Id programId, Id memberId, Integer quantity, Integer offset, String orderBy){
        String query = 'SELECT ' + String.join(new List<String>(fields),',');
        
        Set<Id> badgeIds = new Set<Id>();
        for(FieloPLT__BadgeMember__c bm : [Select FieloPLT__Badge__c FROM FieloPLT__BadgeMember__c WHERE FieloPLT__Member__c =: memberId]){
            badgeIds.add(bm.FieloPLT__Badge__c);
        }

        query += ' FROM FieloPLT__Badge__c WHERE Id In : badgeIds AND FieloPLT__Program__c =: programId';

        //LIMIT
        if(quantity != null){
            query += ' LIMIT ' + quantity;
        }

        //OFFSET
        if(offset != null){
            query += ' OFFSET ' + offset;
        }

        //ORDER by
        if(String.isNotBlank(orderBy)){
            query += ' ORDER BY ' + orderBy;
        }

        return Database.query(query);        
    }

}