src/objects/FieloCMS__Component__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__ComponentLibrary__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Component Library</label>
        <referenceTo>FieloCMS__ComponentLibrary__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Page__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + FieloCMS__Section__r.FieloCMS__Parent__r.FieloCMS__Page__c, FieloCMS__Section__r.FieloCMS__Parent__r.FieloCMS__Page__r.Name, &apos;_self&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Page</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Section to which the component belongs</description>
        <label>Section</label>
        <referenceTo>FieloCMS__Section__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__ComponentLibrary__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Plugin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plugin</label>
        <referenceTo>FieloCMS__Plugin__c</referenceTo>
        <relationshipLabel>Components Library</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Page__c.object
<CustomObject>
    <description>The members’ portal&apos;s pages and templates</description>
    <fields>
        <fullName>FieloCMS__Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>FieloCMS__Site__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Menu</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Plugin__c.object
<CustomObject>
    <label>Plugin</label>
    <nameField>
        <label>Plugin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plugin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Section__c.object
<CustomObject>
    <description>A Section is an area within Pages and Templates which include Subsections.</description>
    <fields>
        <fullName>FieloCMS__Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Page/Template where the Section belongs to.</description>
        <label>Page</label>
        <referenceTo>FieloCMS__Page__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Section where a subsection belongs to.</description>
        <label>Parent</label>
        <referenceTo>FieloCMS__Section__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Site__c.object
<CustomObject>
    <description>A Fielo Site is a content and structure administrator for multiple Salesforce Sites.</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Reward__c.object
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Reward belongs to.</description>
        <inlineHelpText>Choose the Program where the Reward belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_ShoppingCartCtrlTest.cls
@isTest
private class FieloCMSPLT_ShoppingCartCtrlTest {
	
	@isTest static void test_method_one() {
		FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
		insert program;
		FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
		insert member;

		FieloCMSPLT_MockUpFactory.createRewards('Test', 10,  program.Id, 10);

		FieloCMSPLT_ShoppingCartCtrl sc = new FieloCMSPLT_ShoppingCartCtrl();
		List<FieloPLT__Reward__c> rewards = sc.rewards;

		Integer qant = sc.totalItems;

		Map<Id, Integer> mapa = sc.totalPointsMap;




		FieloCMS__Plugin__c plugin1 = new FieloCMS__Plugin__c( Name = 'Default', FieloCMS__Resource__c = 'www.url.com/static1', FieloCMS__ResourceContent__c = 'CSS' );
        FieloCMS__Plugin__c plugin2 = new  FieloCMS__Plugin__c( Name = 'Default', FieloCMS__Resource__c = 'www.url.com/static2', FieloCMS__ResourceContent__c = 'Both' );
        insert new List<FieloCMS__Plugin__c> { plugin1, plugin2 };

        FieloCMS__ComponentLibrary__c componentLibrary1 = new FieloCMS__ComponentLibrary__c( Name = 'Default', FieloCMS__Plugin__c = plugin1.Id );
        FieloCMS__ComponentLibrary__c componentLibrary2 = new FieloCMS__ComponentLibrary__c( Name = 'Default', FieloCMS__Plugin__c = plugin2.Id );
        insert new List<FieloCMS__ComponentLibrary__c> { componentLibrary1, componentLibrary2 };

    //Crea una Pagina con un componente del plugin 1
        FieloCMS__Site__c site = new FieloCMS__Site__c(Name = 'Default');
        insert site;

        FieloCMS__Page__c page =  new FieloCMS__Page__c( Name = 'Default', FieloCMS__Site__c = site.Id);
        insert page;

        FieloCMS__Section__c section = new FieloCMS__Section__c(  FieloCMS__Page__c = page.Id);
        insert section;

        FieloCMS__Section__c subsection = new FieloCMS__Section__c( FieloCMS__Parent__c = section.Id);
        insert subsection;

        FieloCMS__Component__c component1 = new FieloCMS__Component__c( Name = 'Default', FieloCMS__Section__c = subsection.Id, FieloCMS__ComponentLibrary__c = componentLibrary1.id );
        insert component1;

        try{
			FieloCMSPLT_ShoppingCartCtrl.checkout(component1.Id, '{}');
        }catch(Exception e){}
	}
	
}