src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Image__c</fullName>
        <description>Member image.</description>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Member&apos;s status.</description>
        <inlineHelpText>Member&apos;s status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Redemption__c.object
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available points for Rewards.</description>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member who performed the Redemption.</description>
        <inlineHelpText>Member who performed the Redemption.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Redemptions</relationshipLabel>
        <relationshipName>Redemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>The status of this redemption. Possible status values are: Open, Closed, Pending or Rejected.</description>
        <inlineHelpText>Redemption status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__RedemptionItem__c.object
<CustomObject>
    <description>Items in a Redemption order.</description>
    <fields>
        <fullName>FieloPLT__Code__c</fullName>
        <description>Preloaded or randomly generated code included in the Unique voucher.</description>
        <inlineHelpText>Preloaded or randomly generated code included in the Unique voucher.</inlineHelpText>
        <label>Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of Redemption items.</description>
        <inlineHelpText>Number of Redemption items.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Redemption__c</fullName>
        <description>Redemption item ID number.</description>
        <inlineHelpText>Redemption item ID number.</inlineHelpText>
        <label>Redemption</label>
        <referenceTo>FieloPLT__Redemption__c</referenceTo>
        <relationshipLabel>Redemption Items</relationshipLabel>
        <relationshipName>RedemptionItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Reward__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reward from Redemption item.</description>
        <inlineHelpText>Reward from Redemption item.</inlineHelpText>
        <label>Reward</label>
        <referenceTo>FieloPLT__Reward__c</referenceTo>
        <relationshipLabel>Redemption Items</relationshipLabel>
        <relationshipName>RedemptionItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Redemption item status.</description>
        <inlineHelpText>Redemption item status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reverted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloPLT__UniqueCode__c</fullName>
        <description>Voucher number made up of Code and Code Range.</description>
        <formula>IF( ISPICKVAL(FieloPLT__Reward__r.FieloPLT__StockManagement__c, &apos;Controlled By Item&apos;), FieloPLT__Code__c,
   IF ( FieloPLT__CodeRange__c &lt; 10 ,
      FieloPLT__Code__c + &apos;0&apos; + TEXT( FieloPLT__CodeRange__c ),
      FieloPLT__Code__c + RIGHT( TEXT( FieloPLT__CodeRange__c ), 2 )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Voucher number made up of Code and Code Range.</inlineHelpText>
        <label>Unique Code</label>
        <type>Text</type>
    </fields>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FieloPLT__Reward__c.object
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <fields>
        <fullName>FieloPLT__Image__c</fullName>
        <description>Reward image (upload an image or enter URL).</description>
        <inlineHelpText>Choose a Reward image (upload an image or enter URL).</inlineHelpText>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Reward belongs to.</description>
        <inlineHelpText>Choose the Program where the Reward belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloPLT__UniqueVoucher__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, a Voucher may include more than one Reward item.</description>
        <inlineHelpText>When ticked, a Voucher may include more than one Reward item.</inlineHelpText>
        <label>Unique Voucher</label>
        <type>Checkbox</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_RedemptionItemVouCtrl.cls
public with sharing class FieloCMSPLT_RedemptionItemVouCtrl {

    public List<voucherItem> vouchers {get; set;}
    public String voucherCustomVoucher {get; set;}
    public FieloPLT__Program__c program {get; set;}

    public String imageId {get{
        List<Document> docs = [SELECT Id FROM Document WHERE DeveloperName = 'FieloLogoSmallBackEnd' LIMIT 1];
        if(docs.size() > 0){
            return docs[0].Id;
        }
        return null;}}

    public String docURL{get{
        if(docURL == null){
                //docURL = OrganizationUtil.getDocURL();
            }
            return docURL;
        } set;}
    public String orgId{get{return UserInfo.getOrganizationId();}set;}//this is used in the component instead of using $Organization.Id directly in VisualForce because using the attribute the image can be cached


    public with sharing class voucherItem {

        public FieloPLT__RedemptionItem__c redemptionItem {get;set;}
        public String image{get;set;}
        public Integer voucherNum {get;set;}
        public String instructionsReward{get;set;}
        public String instructionsVoucher{get;set;}

        public voucherItem (FieloPLT__RedemptionItem__c redemptionItem, String imageId, Integer i ,String instructionsVoucher, String instructionsReward ) {
            this.redemptionItem = redemptionItem;
            this.image = imageId;
            this.voucherNum = i;
            this.instructionsVoucher = instructionsVoucher;
            if(redemptionItem.FieloPLT__Reward__r.FieloCMSPLT_InstructionsRichText__c != null){
                this.instructionsReward = redemptionItem.FieloPLT__Reward__r.FieloCMSPLT_InstructionsRichText__c;
            }else{
                this.instructionsReward = instructionsReward;
            }
        }
    }

    public FieloCMSPLT_RedemptionItemVouCtrl(){
        String idOrden = ApexPages.currentPage().getParameters().get('ordenId');
        String voucherId = ApexPages.currentPage().getParameters().get('voucherId');

        if(String.isNotBlank(idOrden) || String.isNotBlank(voucherId)){
            List<FieloPLT__RedemptionItem__c> redemptionItem;
            String query = 'SELECT Name, FieloPLT__Redemption__r.FieloPLT__Member__r.FieloPLT__Program__c, LastModifiedDate, Id, FieloPLT__Redemption__c, FieloPLT__Quantity__c, FieloPLT__Status__c, FieloPLT__Reward__c, FieloPLT__Reward__r.FieloPLT__Image__c, FieloPLT__Reward__r.FieloCMSPLT_InstructionsRichText__c, FieloPLT__Reward__r.FieloPLT__UniqueVoucher__c, FieloPLT__UniqueCode__c, FieloPLT__Reward__r.Name, FieloPLT__Code__c, CreatedDate, CreatedById';
            List<Schema.FieldSetMember> fieldsRedemptionItem = Schema.SObjectType.FieloPLT__RedemptionItem__c.fieldSets.FieloCMSPLT_Voucher.getFields();

            for(Schema.FieldSetMember f : fieldsRedemptionItem){
                if(!query.contains(f.getFieldPath())){
                    query += ', '+f.getFieldPath();
                }
            }

            query += ' FROM FieloPLT__RedemptionItem__c';

            if(String.isNotBlank(idOrden)){
                query += ' WHERE FieloPLT__Redemption__c =: idOrden';
            }else if(String.isNotBlank(voucherId)){
                query += ' WHERE Id =: voucherId';
            }
            redemptionItem = Database.query(query);
            if(!redemptionItem.isEmpty()){
                program = new FieloCMSPLT_ProgramsSelector(new Set<String>{'FieloCMSPLT_ShowVoucherCode__c', 'FieloCMSPLT_CustomVoucherCss__c', 'FieloCMSPLT_VoucherInstructions__c', 'FieloCMSPLT_RewardInstructions__c'}).selectById(new Set<Id>{redemptionItem[0].FieloPLT__Redemption__r.FieloPLT__Member__r.FieloPLT__Program__c})[0];
            }else{
                program = new FieloCMSPLT_ProgramsSelector(new Set<String>{'FieloCMSPLT_ShowVoucherCode__c', 'FieloCMSPLT_CustomVoucherCss__c', 'FieloCMSPLT_VoucherInstructions__c', 'FieloCMSPLT_RewardInstructions__c'}).selectByDefault();
            }

            voucherCustomVoucher = program.FieloCMSPLT_CustomVoucherCss__c;

            vouchers = new List<voucherItem>();
            Integer i = 0;
            for(FieloPLT__RedemptionItem__c r : redemptionItem){
                i++;
                vouchers.add(new voucherItem(r, r.FieloPLT__Reward__r.FieloPLT__Image__c, i, program.FieloCMSPLT_VoucherInstructions__c, program.FieloCMSPLT_RewardInstructions__c));
                i = ( i == 2 )?0:i;
            }
        }
    }
}