src/objects/FieloCMS__Component__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__DetailParameter__c</fullName>
        <defaultValue>&apos;id&apos;</defaultValue>
        <description>The name of the parameter that a list will use to send to a detail component</description>
        <label>Detail parameter</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieloCMS__FieldSet__c</fullName>
        <label>FieldSet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Limit__c</fullName>
        <defaultValue>6</defaultValue>
        <inlineHelpText>Set the number of items to show per page</inlineHelpText>
        <label>Items per Page</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloCMS__OrderBy__c</fullName>
        <description>Used on the Catalogo Component to give to the user the option to order the rewards</description>
        <label>Order By</label>
        <picklist>
            <picklistValues>
                <fullName>Name ASC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloCMS__RecordId__c</fullName>
        <description>This field will be used just in memory, containing temporarily the Id of the record that the detail is going to be shown.</description>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Member&apos;s status.</description>
        <inlineHelpText>Member&apos;s status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Redemption__c.object
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available points for Rewards.</description>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member who performed the Redemption.</description>
        <inlineHelpText>Member who performed the Redemption.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Redemptions</relationshipLabel>
        <relationshipName>Redemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>The status of this redemption. Possible status values are: Open, Closed, Pending or Rejected.</description>
        <inlineHelpText>Redemption status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__RedemptionItem__c.object
<CustomObject>
    <description>Items in a Redemption order.</description>
    <fields>
        <fullName>FieloPLT__Redemption__c</fullName>
        <description>Redemption item ID number.</description>
        <inlineHelpText>Redemption item ID number.</inlineHelpText>
        <label>Redemption</label>
        <referenceTo>FieloPLT__Redemption__c</referenceTo>
        <relationshipLabel>Redemption Items</relationshipLabel>
        <relationshipName>RedemptionItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Redemption item status.</description>
        <inlineHelpText>Redemption item status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reverted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RedemptionItemAPI.cls
global with sharing class RedemptionItemAPI implements FieloCMS.DataInterface{
    
    global Map<Id, Object> getBulkData(List<FieloCMS__Component__c> components){                
        Map<Id,Object> newMapData = new Map<Id,Object>();
        //Prepare all the queries
        for(FieloCMS__Component__c c : components){            
            if(c.FieloCMS__Limit__c == null)
                c.FieloCMS__Limit__c = 5;
            
            String whereCondition = 'FieloPLT__Redemption__r.FieloPLT__Member__c = \'' + MemberService.getCurrentMemberId() + '\'';
            if(c.FieloCMS__RecordId__c != null){
                //Id redemptionId = ApexPages.CurrentPage().getParameters().get(c.FieloCMS__DetailParameter__c);
                whereCondition += ' AND FieloPLT__Redemption__c = \'' + c.FieloCMS__RecordId__c + '\'';
            }else{
                whereCondition += ' AND FieloPLT__Redemption__r.FieloPLT__Status__c != \'Open\'';
            }
            if(!String.isBlank(c.FieloCMS__OrderBy__c)){
                whereCondition += ' ORDER BY ' + c.FieloCMS__OrderBy__c;
            }
            whereCondition += ' LIMIT ' + String.valueOf(c.FieloCMS__Limit__c);
            whereCondition += ' OFFSET 0';
            newMapData.put(c.Id, Database.query('SELECT ' + String.join(new List<String>(OrganizationUtil.getFieldSet(c.FieloCMS__FieldSet__c)), ',') + ' FROM FieloPLT__RedemptionItem__c WHERE ' + whereCondition));
        }
        return newMapData;
    }

    global List<sObject> getData(FieloCMS__Component__c component, Integer pageNumber, String orderBy, String filters){
        
        if(component.FieloCMS__Limit__c == null)
            component.FieloCMS__Limit__c = 5;

        //Calculate the offset from the Page Number
        Integer offset = Integer.valueOf(component.FieloCMS__Limit__c * (pageNumber - 1));

        Id recordId;
        if(String.isNotBlank(filters)){
            List<FilterService.FilterWrapper> filtersList = (List<FilterService.FilterWrapper>) JSON.deserialize(filters, List<FilterService.FilterWrapper>.class);
            if(!filtersList.isEmpty()){
                for(FilterService.FilterWrapper filter: filtersList ){
                    if(filter.field == 'FieloCMS__RecordId__c' && filter.value != null){
                        recordId = filter.value;
                    }
                }
            }
        }

        String whereCondition = 'FieloPLT__Redemption__r.FieloPLT__Member__c = \'' + MemberService.getCurrentMemberId() + '\'';
        if(recordId != null){
            //Id redemptionId = ApexPages.CurrentPage().getParameters().get(c.FieloCMS__DetailParameter__c);
            whereCondition += ' AND FieloPLT__Redemption__c = \'' + recordId + '\'';
        }else{
            whereCondition += ' AND FieloPLT__Redemption__r.FieloPLT__Status__c != \'Open\'';
        }

        if(orderBy != null && orderBy != ''){
            whereCondition += ' ORDER BY ' + orderBy;
        }        
        whereCondition += ' LIMIT ' + String.valueOf(component.FieloCMS__Limit__c);
        whereCondition += ' OFFSET ' + String.valueOf(offset);

        List<String> fields = new List<String>(OrganizationUtil.getFieldSet(component.FieloCMS__FieldSet__c));

        Schema.DescribeSObjectResult objectDescribe = Schema.describeSObjects(new List<String>{'FieloPLT__RedemptionItem__c'})[0];
        Set<String> picklistTypes = new Set<String>{'PICKLIST','MULTIPICKLIST'};
        
        for(Integer i = 0 ; i < fields.size() ; ) {
            String field = fields.get(i);
            if(objectDescribe.fields.getMap().containskey(field.toLowerCase()) && picklistTypes.contains(objectDescribe.fields.getMap().get(field.toLowerCase()).getDescribe().getType().name())){
                fields.remove(i);
                fields.add('toLabel(' + field + ')');
            }else{
                i++;
            }
        }

        return Database.query('SELECT ' + String.join(fields, ',') + ' FROM FieloPLT__RedemptionItem__c WHERE ' + whereCondition);
    }
}