src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <fields>
        <fullName>FieloPLT__ActualPointCost__c</fullName>
        <description>It translates Transaction Points into real cost.</description>
        <inlineHelpText>It translates Transaction Points into real cost.</inlineHelpText>
        <label>Actual Point Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FieloPLT__CategoryInjectQuery__c</fullName>
        <description>Field that filters Category by means of conditions.</description>
        <inlineHelpText>Field that filters Category by means of conditions.</inlineHelpText>
        <label>Category Inject Query</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieloPLT__ExpirationPeriod__c</fullName>
        <description>It sets the active Points period.</description>
        <inlineHelpText>Set the active Points period.</inlineHelpText>
        <label>Expiration Period</label>
        <picklist>
            <controllingField>FieloPLT__ExpirationMode__c</controllingField>
            <picklistValues>
                <fullName>3</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this option makes this your default Program.</description>
        <inlineHelpText>When ticked, Program becomes your Default Program.</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__NumberOfVoucherDigits__c</fullName>
        <description>Number of digits displayed on the voucher.</description>
        <inlineHelpText>Set the number of digits displayed on the voucher.</inlineHelpText>
        <label>Number of Voucher Digits</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__OnlineTransactionProcessing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When ticked, Transactions are processed online when recorded. Otherwise, all transactions are processed offline once a day.</description>
        <inlineHelpText>When ticked, Transactions are processed online when recorded.</inlineHelpText>
        <label>Online Transaction Processing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__RequestMemberAuthorization__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, new Members need to be approved before being included in the Program and an Authorization Workflow needs to be established.</description>
        <inlineHelpText>When ticked, new Members need to be approved before being included in the Program.</inlineHelpText>
        <label>Request Member Authorization</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__RequestRedemptionAuthorization__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, new Redemptions need to be approved beforehand.</description>
        <inlineHelpText>When ticked, new Redemptions need to be approved beforehand.</inlineHelpText>
        <label>Request Redemption Authorization</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__RequestTransactionAuthorization__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, new Transactions need to be approved beforehand.</description>
        <inlineHelpText>When ticked, new Transactions need to be approved beforehand.</inlineHelpText>
        <label>Request Transaction Authorization</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__RewardInjectQuery__c</fullName>
        <description>Field that filters Rewards by means of conditions.</description>
        <inlineHelpText>Field that filters Rewards by means of conditions.</inlineHelpText>
        <label>Reward Inject Query</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieloPLT__SegmentInjectQuery__c</fullName>
        <description>Field that filters Segments by means of conditions.</description>
        <inlineHelpText>Field that filters Segments by means of conditions.</inlineHelpText>
        <label>Segment Inject Query</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieloPLT__UseAgreement__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Members need to accept the terms and conditions. This option is always checked by default.</description>
        <inlineHelpText>When checked, Members need to accept the terms and conditions to operate in the Site.</inlineHelpText>
        <label>Use Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__UserCreationClass__c</fullName>
        <description>Class for User creation reflection.</description>
        <inlineHelpText>Enter the class for User creation reflection.</inlineHelpText>
        <label>User Creation Class</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__PublicSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Application configuration.</description>
    <label>Public Settings</label>
</CustomObject>

src/classes/FieloCMSPLT_ProgramsSelector.cls
public with sharing class FieloCMSPLT_ProgramsSelector extends FieloCMSPLT_SObjectSelector{
  public List<Schema.SObjectField> getSObjectFieldList(){
    return new List<Schema.SObjectField> {
        FieloPLT__Program__c.Id,
        FieloPLT__Program__c.Name,
        FieloPLT__Program__c.FieloPLT__RequestMemberAuthorization__c,
        FieloPLT__Program__c.FieloPLT__UserCreationClass__c
      };
  }

  public Schema.SObjectType getSObjectType(){
    return FieloPLT__Program__c.sObjectType;
  }

  public List<FieloPLT__Program__c> selectById(Set<Id> idSet){
    return (List<FieloPLT__Program__c>)selectSObjectsById(idSet);
  }

    private Id lastProgramId;
  private FieloPLT__Program__c staticProgram;
  public FieloPLT__Program__c selectStaticProgram(Id programId){
    if(lastProgramId == null || lastProgramId != programId){
      lastProgramId = programId;
      Set<String> fieldSet = getFieldList();
      setFieldList(getAllFields());
      staticProgram = selectById(new Set<Id>{programId})[0];
      setFieldList(fieldSet);
    }

        FieloPLT__Program__c returnProgram = new FieloPLT__Program__c(Id = staticProgram.Id);
        for(String field : getFieldList()){
            try{
                returnProgram.put(field, staticProgram.get(field));
            }catch(Exception e){
                return staticProgram;
            }
        }
        return returnProgram;
  }

  public FieloCMSPLT_ProgramsSelector(Set<String> fields){
    super(fields);
  }

  public FieloCMSPLT_ProgramsSelector(){
    super();
  }

  public FieloCMSPLT_ProgramsSelector(Boolean allFields){
    if(!allFields){
      this();
    }else{
      setFieldList(getAllFields());
    }
  }

  private static Set<String> getAllFields(){
        //String query = ' ';
        Set<String> fieldSet = new Set<String>();
        FieloPLT__PublicSettings__c settings = FieloPLT__PublicSettings__c.getOrgDefaults();
        //If the Custom Setting is not empty then used the Optimized query
        if(settings.FieloPLT__OptimizedProgramQuery__c){
            //If its the Default Case use only Standard Field
            fieldSet.addAll(new Set<String>{'Name','FieloPLT__RewardInjectQuery__c','FieloPLT__SegmentInjectQuery__c','FieloPLT__CategoryInjectQuery__c','FieloPLT__ExpirationPeriod__c','FieloPLT__NumberOfVoucherDigits__c','FieloPLT__ActualPointCost__c','FieloPLT__RequestRedemptionAuthorization__c','FieloPLT__RequestMemberAuthorization__c','RequestTransactionAuthorization__c','FieloPLT__RequestTransactionAuthorization__c','FieloPLT__OnlineTransactionProcessing__c','FieloPLT__UseAgreement__c','FieloPLT__UserCreationClass__c'});
            for(Schema.FieldSetMember fsm : Schema.SObjectType.FieloPLT__Program__c.fieldSets.FieloPLT__ProgramQuery.getFields()){
                fieldSet.add(fsm.getFieldPath());
            }
        }else{
            //Use Describe to get all the Fields
            Map<String, Schema.SObjectField> fields = FieloPLT__Program__c.SObjectType.getDescribe().fields.getMap();
            Set<String> fieldFilter = new Set<String> {'CreatedById', 'IsDeleted', 'OwnerId', 'LastModifiedDate', 'LastModifiedById', 'SystemModstamp'};
            for(Schema.SObjectField field : fields.values()){
                fieldSet.add(field.getDescribe().getName());
            }
        }
        return fieldSet;
    }

  //private static FieloPLT__Program__c programBySiteUrl;
  public FieloPLT__Program__c selectBySiteUrl(String siteDomain){
    //if(programBySiteUrl == null){
          if(siteDomain != null) siteDomain = siteDomain.replace('.secure.','.');
          System.debug(loggingLevel.Error, '*** siteDomain: ' + siteDomain);

      assertIsAccessible();
      List<FieloPLT__Program__c> programs = (List<FieloPLT__Program__c>) Database.query(
          String.format(
          'select {0} ' +
            'from {1} ' +
            'where FieloCMSPLT_SiteDomain__c =: siteDomain ' +
            'order by {2}',
          new List<String> {
            getFieldListString(),
            getSObjectName(),
            getOrderBy() } ) );

          if(!programs.isEmpty()){
              //programBySiteUrl = programs.get(0);
              return programs.get(0);
          }else{
              //programBySiteUrl = selectByDefault();
              return selectByDefault();
          }
      //}
      //return programBySiteUrl;
  }

  /*FieloPLT__Program__c p = getProgramByDomain();
    FieloPLT__Program__c returnProgram = new FieloPLT__Program__c(Id = p.Id);
    Map<String, Schema.SObjectField> fieldsDescribe = FieloPLT__Program__c.SObjectType.getDescribe().fields.getMap();
    if(fields != null){
        for(String field : fields){
            try{
                returnProgram.put(field, p.get(field));
            }catch(Exception e){
                return p;
            }
        }
    }
    return returnProgram;*/

  private static FieloPLT__Program__c programDefault;
  public FieloPLT__Program__c selectByDefault(){
    programDefault = (FieloPLT__Program__c) Database.query(
        String.format(
        'select {0} ' +
          'from {1} ' +
          'where FieloPLT__IsDefault__c = true ' +
          'order by {2}',
        new List<String> {
          getFieldListString(),
          getSObjectName(),
          getOrderBy() } ) );

    return programDefault;
  }

  public List<FieloPLT__Program__c> selectAll(){
    return (List<FieloPLT__Program__c>) Database.query(
      String.format(
      'select {0} ' +
        'from {1} ' +
        'order by {2}',
      new List<String> {
        getFieldListString(),
        getSObjectName(),
        getOrderBy() } ) );
  }

  /*
   * For more examples see https://github.com/financialforcedev/fflib-apex-common-samplecode
   *
  public List<FieloPLT__Program__c> selectBySomethingElse(List<String> somethings)
  {
    assertIsAccessible();
    return (List<FieloPLT__Program__c>) Database.query(
        String.format(
        'select {0} ' +
          'from {1} ' +
          'where Something__c in :somethings ' +
          'order by {2}',
        new List<String> {
          getFieldListString(),
          getSObjectName(),
          getOrderBy() } ) );
  }
   */
}