src/objects/FieloPLT__Badge__c.object
<CustomObject>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__BadgeMember__c.object
<CustomObject>
    <description>Badges obtained by each Member.</description>
    <fields>
        <fullName>FieloPLT__Badge__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Badge granted to a Member.</description>
        <inlineHelpText>Badge granted to a Member.</inlineHelpText>
        <label>Badge</label>
        <referenceTo>FieloPLT__Badge__c</referenceTo>
        <relationshipLabel>Badge Members</relationshipLabel>
        <relationshipName>BadgesMembers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Member who obtained a Badge.</description>
        <inlineHelpText>Member who obtained a Badge.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Badge Members</relationshipLabel>
        <relationshipName>BadgesMembers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Badge Member</label>
    <nameField>
        <label>BadgeMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_BadgeServiceTest.cls
@isTest
private class FieloCMSPLT_BadgeServiceTest{
    @isTest
    static void itShould_1(){
    
        // Given
        FieloCMSPLT_MockupFactory.setProgramAndMember();
        
        FieloPLT__Program__c program = [SELECT Id FROM FieloPLT__Program__c];
        
        FieloPLT__Member__c member = [SELECT Id FROM FieloPLT__Member__c];
        
        FieloPLT__Badge__c badge = new FieloPLT__Badge__c(Name = 'Test', FieloPLT__Program__c = program.Id);
        insert badge;
        
        FieloPLT__BadgeMember__c badgeMember = new FieloPLT__BadgeMember__c(FieloPLT__Member__c = member.Id, FieloPLT__Badge__c = badge.Id);
        insert badgeMember;
        
        List<FieloPLT__Badge__c> badges = FieloCMSPLT_BadgeService.getBadges(new Set<String>{'Name'},program.Id,member.Id,10,0,null);    
    
    }
}