src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SessionCache__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>MemberId__c</fullName>
        <label>Member Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SessionId__c</fullName>
        <label>Session Id</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Session Cache</label>
</CustomObject>

src/classes/FieloCMSPLT_MemberService.cls
public with sharing class FieloCMSPLT_MemberService {

	public static FieloPLT__Member__c getCurrentMember(Set<String> fields){
        return new FieloCMSPLT_MembersSelector(fields).selectById(new Set<Id>{getCurrentMemberId()})[0];
    }

    private static Id memId;
    public static Id getCurrentMemberId(){
        if(UserInfo.getUserType() == 'Guest')
            return null;

        if(memId == null){
            SessionCache__c sessionCache = SessionCache__c.getInstance(UserInfo.getUserId());
            if((sessionCache.SessionId__c == UserInfo.getSessionId() || UserInfo.getUserType() == 'Standard') && sessionCache.MemberId__c != null){
                memId = sessionCache.MemberId__c;
            }else{
                try{
                    List<FieloPLT__Member__c> members = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE FieloPLT__User__c =: UserInfo.getUserId()];
                    if(members.size() == 1){
                        memId = members[0].Id;
                    }else{
                        Id programId = ProgramService.getProgramByDomain().Id;
                        for(FieloPLT__Member__c m : members){
                            if(m.FieloPLT__Program__c == programId){
                                memId = m.Id;
                                break;
                            }
                        }

                    }
                }catch(Exception e){
                    return null;
                }
            }
        }

        return memId;
        //return 'a0D41000000y2fM';
    }

    public static void setCurrentMemberId(Id memberId){
        //ApexPages.currentPage().setCookies(new Cookie[]{new Cookie('memberId', memberId, null, -1,true),new Cookie('sessionMemberId', UserInfo.getSessionId(), null, -1,false)});

        SessionCache__c sessionCache = SessionCache__c.getInstance(UserInfo.getUserId());
        sessionCache.SessionId__c = UserInfo.getSessionId();
        sessionCache.MemberId__c = memberId;
        upsert sessionCache;
    }

    public static PageReference setPasswordAndLogin(Id memberId, String password){
        if(memberId == null){
            throw new FieloException(Label.MemberIdRequired);
        }else if(String.isBlank(password)){
            throw new FieloException(Label.PasswordIsRequired);
        }
        Savepoint sp = Database.setSavepoint();
        try{
            setPassword(memberId, password);
            return login(memberId, password);
        }catch(Exception e){
            Database.rollback(sp);
            throw e;
        }
    }


    public static PageReference login(Id memberId, String password){
        if(memberId == null){
            throw new FieloException(Label.MemberIdRequired);
        }else if(String.isBlank(password)){
            throw new FieloException(Label.PasswordIsRequired);
        }
        Savepoint sp = Database.setSavepoint();
        try{
            FieloPLT__Member__c member = new FieloCMSPLT_MembersSelector().selectById(new Set<Id>{memberId})[0];
            User user = [SELECT UserName FROM User WHERE Id =: member.FieloPLT__User__c LIMIT 1];
            return Site.login(user.UserName, password, null);
        }catch(Exception e){
            Database.rollback(sp);
            throw e;
        }
    }

    public static void setPassword(Id memberId, String password){
        if(memberId == null){
            throw new FieloException(Label.MemberIdRequired);
        }else if(String.isBlank(password)){
            throw new FieloException(Label.PasswordIsRequired);
        }
        Savepoint sp = Database.setSavepoint();
        try{
            FieloPLT__Member__c member = new FieloCMSPLT_MembersSelector(new Set<String>{'FieloPLT__User__c'}).selectById(new Set<Id>{memberId})[0];
            system.setPassword(member.FieloPLT__User__c, password);
        }catch(Exception e){
            Database.rollback(sp);
            throw e;
        }
    }

}