src/objects/FieloCMS__Layout__c.object
<CustomObject>
    <description>A Layout refers to the branding style given to Sites, by means of related Themes and Templates.</description>
    <fields>
        <fullName>FieloCMS__Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>FieloCMS__Site__c</referenceTo>
        <relationshipLabel>Layouts</relationshipLabel>
        <relationshipName>ProgramPortals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Layout</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Site__c.object
<CustomObject>
    <description>A Fielo Site is a content and structure administrator for multiple Salesforce Sites.</description>
    <fields>
        <fullName>FieloCMS__Layout__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Default Layout</description>
        <label>Layout</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>FieloCMS__Layout__c.FieloCMS__Site__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FieloCMS__Layout__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__SiteId__c</fullName>
        <label>Salesforce Site</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_SiteLoginCtrl.cls
global with sharing class FieloCMSPLT_SiteLoginCtrl {
    
    @RemoteAction
    global static FieloCMS.RemoteActionResult login(String userName, String password){        
        FieloCMS.RemoteActionResult result = new FieloCMS.RemoteActionResult();                
        Pagereference redirectPage;

        String redirectURL;
        String siteId = site.getSiteId();
        List<FieloCMS__Layout__c> ll = [SELECT Id FROM FieloCMS__Layout__c WHERE FieloCMS__Site__r.FieloCMS__SiteId__c = :siteId AND Name = 'Private' ];
        if ( !ll.isEmpty() ) {
            redirectURL = '?layoutid=' + ll.get(0).Id;
        }
        
        try{
            redirectPage = FieloCMSPLT_LoginService.login(username, password, redirectURL);            

            if(redirectPage != null){
                redirectPage.getParameters().put('retURL', redirectPage.getParameters().get('retURL') + redirectURL);

                result.redirectURL = redirectPage.getUrl().replace('%2Fapex','');
            }
        }catch(FieloCMSPLT_Exception e){
            result.redirectURL = '';
            result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(e));
        }catch(FieloPLT.FieloException e){
            result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(e));
        }
        
        if(ApexPages.hasMessages()){
            result.redirectURL = '';
            for(ApexPages.Message m : ApexPages.getMessages()){
                result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(m));
            }
        }        
        return result;
    }

    @RemoteAction
    global static FieloCMS.RemoteActionResult forgotPassword(String userName){        
        FieloCMS.RemoteActionResult result = new FieloCMS.RemoteActionResult();                
        Pagereference redirectPage;
        try{
            redirectPage = FieloCMSPLT_LoginService.forgotPassword(username);
            if(redirectPage != null) result.redirectURL = redirectPage.getUrl();
            result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(new ApexPages.Message(ApexPages.SEVERITY.Info, Label.site.temp_password_sent + '<a href="/" >' + Label.FieloCMSPLT_GoToHome + '</a>')));
        }catch(FieloCMSPLT_Exception e){
            result.redirectURL = '';
            result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(e));
        }catch(FieloPLT.FieloException e){
            result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(e));
        }
        
        if(ApexPages.hasMessages()){
            result.redirectURL = '';
            for(ApexPages.Message m : ApexPages.getMessages()){
                result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(m));
            }
        }

        return result;
    }

}