src/objects/FieloAlpha__Program__c.object
<CustomObject>
    <description>Settings of each of your Fielo programs. You can create up to XXXX different programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloAlpha__RedemptionRule__c.object
<CustomObject>
    <customHelpPage>FieloAlpha__RedemptionRuleHelpBackEnd</customHelpPage>
    <description>Arbitrary groups to which members can belong. You can create segments by age, by location, etc.</description>
    <fields>
        <fullName>FieloAlpha__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>FieloAlpha__Program__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PackageInstallation.cls
public without sharing class PackageInstallation implements InstallHandler {
	public void onInstall(InstallContext context){
		if(context.PreviousVersion() == null){
            install(context.installerId());
        }
	}

	public void install(Id userId){
		createPublicAndPrivateSegments();
	}

	public static void createPublicAndPrivateSegments(){
		List<RecordType> recordTypes = [SELECT Id FROM RecordType WHERE (DeveloperName = 'Private' OR DeveloperName = 'Public') AND SObjectType = 'FieloAlpha__RedemptionRule__c' ORDER BY DeveloperName ASC];
		List<FieloAlpha__RedemptionRule__c> toInsert = new List<FieloAlpha__RedemptionRule__c>();
		for(FieloAlpha__Program__c p : [SELECT Id FROM FieloAlpha__Program__c]){
			toInsert.add(new FieloAlpha__RedemptionRule__c(Name = 'Registered', RecordTypeId = recordTypes[0].Id, FieloAlpha__Program__c = p.Id));
			toInsert.add(new FieloAlpha__RedemptionRule__c(Name = 'Guest', RecordTypeId = recordTypes[1].Id, FieloAlpha__Program__c = p.Id));
		}
		insert toInsert;
	}
}