src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Member is a Manager of the Organization Account.</description>
        <inlineHelpText>Member is a Manager of their Organization Account.</inlineHelpText>
        <label>Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__OrganizationAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization account linked to the Organization Contributor account.</description>
        <inlineHelpText>Choose Organization account where the Organization Contributor Member belongs to.</inlineHelpText>
        <label>Organization Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Member must be an &quot;Organization Account&quot; and belong to the same Program.</errorMessage>
            <filterItems>
                <field>FieloPLT__Member__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Organization Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Members (Organization Account)</relationshipLabel>
        <relationshipName>FieloAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Member&apos;s status.</description>
        <inlineHelpText>Member&apos;s status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Redemption__c.object
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available points for Rewards.</description>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member who performed the Redemption.</description>
        <inlineHelpText>Member who performed the Redemption.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Redemptions</relationshipLabel>
        <relationshipName>Redemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>The status of this redemption. Possible status values are: Open, Closed, Pending or Rejected.</description>
        <inlineHelpText>Redemption status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_CheckoutCtrl.cls
global with sharing class FieloCMSPLT_CheckoutCtrl implements FieloCMS.ViewSubComponentInterface {

    global ApexPages.Component getSubComponent(FieloCMS.Field field, SObject record){        
        Component.FieloCMSPLT_Checkout checkout = new Component.FieloCMSPLT_Checkout();
        if(record != null){
            checkout.record = record;
        }else{
            checkout.expressions.record = '{!record}';
        }        
        checkout.field = field;        
        return checkout;
    }

    @RemoteAction
    global static FieloCMS.RemoteActionResult checkout(Id rewardId, Integer quantity, String detailUrl){                        
        FieloCMS.RemoteActionResult result = new FieloCMS.RemoteActionResult();
        Savepoint sp = Database.setSavepoint();
        try{  
            FieloPLT__Member__c loggedMember = FieloCMSPLT_MemberService.getCurrentMember(new Set<String>{'FieloPLT__OrganizationFieloCMSPLT_Account__c','FieloPLT__Type__c','FieloPLT__IsManager__c'});
            Id memberId = (loggedMember.FieloPLT__Type__c == 'Organization Contributor' && loggedMember.FieloPLT__OrganizationAccount__c != null && loggedMember.FieloPLT__IsManager__c) ? loggedMember.FieloPLT__OrganizationAccount__c : loggedMember.Id;
                          
            List<FieloPLT__Redemption__c> redemptions = FieloPLT.RedemptionService.createRedemptions(new Map<Id,Integer>{rewardId => quantity}, memberId);
            if(redemptions[0].FieloPLT__Status__c == 'Closed'){                
                result.redirectURL = detailUrl + redemptions[0].Id;
            }else{
                result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(new ApexPages.Message(ApexPages.SEVERITY.Info, Label.FieloCMSPLT_InfoRedemptionApproval)));
                result.refresh.add( new FieloCMS.RemoteActionResult.RemoteActionRefresh('quantity', '1'));
            }            
        }catch(Exception e){
            Database.rollBack(sp);
            result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(e));
        }

        if(ApexPages.hasMessages()){
            result.redirectURL = '';
            for(ApexPages.Message m : ApexPages.getMessages()){
                result.addMessage(new FieloCMS.RemoteActionResult.RemoteActionMessage(m));
            }
        }

        return result;
    }
}