src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Member&apos;s status.</description>
        <inlineHelpText>Member&apos;s status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Redemption__c.object
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available points for Rewards.</description>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member who performed the Redemption.</description>
        <inlineHelpText>Member who performed the Redemption.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Redemptions</relationshipLabel>
        <relationshipName>Redemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Origin__c</fullName>
        <description>Source from which the Redemption order was generated.</description>
        <inlineHelpText>Source from which the Redemption order was generated.</inlineHelpText>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>BackEnd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FrontEnd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>The status of this redemption. Possible status values are: Open, Closed, Pending or Rejected.</description>
        <inlineHelpText>Redemption status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__RedemptionItem__c.object
<CustomObject>
    <description>Items in a Redemption order.</description>
    <fields>
        <fullName>FieloPLT__Redemption__c</fullName>
        <description>Redemption item ID number.</description>
        <inlineHelpText>Redemption item ID number.</inlineHelpText>
        <label>Redemption</label>
        <referenceTo>FieloPLT__Redemption__c</referenceTo>
        <relationshipLabel>Redemption Items</relationshipLabel>
        <relationshipName>RedemptionItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Reward__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reward from Redemption item.</description>
        <inlineHelpText>Reward from Redemption item.</inlineHelpText>
        <label>Reward</label>
        <referenceTo>FieloPLT__Reward__c</referenceTo>
        <relationshipLabel>Redemption Items</relationshipLabel>
        <relationshipName>RedemptionItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Redemption item status.</description>
        <inlineHelpText>Redemption item status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reverted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Redemption Item</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemption Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FieloPLT__Reward__c.object
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_RedemptionItemsSelector.cls
public class FieloCMSPLT_RedemptionItemsSelector extends FieloCMSPLT_SObjectSelector{

	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField> {
				FieloPLT__RedemptionItem__c.Id
			};
	}

	public FieloCMSPLT_RedemptionItemsSelector(Set<String> fields){
		super(fields);
	}

	public FieloCMSPLT_RedemptionItemsSelector(){
		super();
	}

	public Schema.SObjectType getSObjectType(){
		return FieloPLT__RedemptionItem__c.sObjectType;
	}

	public List<FieloPLT__RedemptionItem__c> selectById(Set<ID> idSet){
		return (List<FieloPLT__RedemptionItem__c>) selectSObjectsById(idSet);
	}

	public List<FieloPLT__RedemptionItem__c> selectByMemberOriginStatusAndReward(Id rewardId, String status, String origin, Id memberId){
		assertIsAccessible();
		return (List<FieloPLT__RedemptionItem__c>) Database.query(
				String.format(
				'select {0} ' +
				  'from {1} ' +
				  'where FieloPLT__Reward__c =: rewardId AND FieloPLT__Redemption__r.FieloPLT__Status__c =: status AND FieloPLT__Redemption__r.FieloPLT__Origin__c =: origin AND FieloPLT__Redemption__r.FieloPLT__Member__c =: memberId ' + 
				  'order by {2}',
				new List<String> {
					getFieldListString(),
					getSObjectName(),					
					getOrderBy() } ) );
	}	

	public List<FieloPLT__RedemptionItem__c> selectByRedemptionAndRewards(Id redemptionId, Set<Id> rewardIds){
		assertIsAccessible();
		return (List<FieloPLT__RedemptionItem__c>) Database.query(
			String.format(
			'select {0} ' +
			 	'from {1} ' +
			 	'where FieloPLT__Redemption__c =: redemptionId AND FieloPLT__Reward__c IN: rewardIds ' + 
			 	'order by {2}',
			new List<String> {
				getFieldListString(),
				getSObjectName(),
				getOrderBy() } ) );
	}

	/*
	 * For more examples see https://github.com/financialforcedev/fflib-apex-common-samplecode
	 * 
	public List<FieloPLT__RedemptionItem__c> selectBySomethingElse(List<String> somethings)
	{
		assertIsAccessible();
		return (List<FieloPLT__RedemptionItem__c>) Database.query(
				String.format(
				'select {0} ' +
				  'from {1} ' +
				  'where Something__c in :somethings ' + 
				  'order by {2}',
				new List<String> {
					getFieldListString(),
					getSObjectName(),
					getOrderBy() } ) );
	}
	 */
}