src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_MemberServiceTest.cls
@isTest
private class FieloCMSPLT_MemberServiceTest{

	@isTest
	static void itShould1(){
		
		FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
		insert program;
		FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
		insert member;
		
		FieloCMSPLT_MemberService.getCurrentMember(new Set<String>{'Id','Name'});


		FieloCMSPLT_MemberService.setCurrentMemberId(member.Id);


		try{
			FieloCMSPLT_MemberService.setPasswordAndLogin(null, null);
		}catch(Exception e){}

		try{
			FieloCMSPLT_MemberService.setPasswordAndLogin(member.Id, null);
		}catch(Exception e){}
		FieloCMSPLT_MemberService.setPasswordAndLogin(member.Id, 'qwer1234');

		try{
			FieloCMSPLT_MemberService.login(null, null);
		}catch(Exception e){}

		try{
			FieloCMSPLT_MemberService.login(member.Id, null);
		}catch(Exception e){}
		FieloCMSPLT_MemberService.login(member.Id, 'qwer1234');

		try{
			FieloCMSPLT_MemberService.setPassword(null, null);
		}catch(Exception e){}

		try{
			FieloCMSPLT_MemberService.setPassword(member.Id, null);
		}catch(Exception e){}
		FieloCMSPLT_MemberService.setPassword(member.Id, '1234qwer');
	}

	@isTest
	static void itShould2(){
		
		FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
		insert program;
		FieloPLT__Program__c program2 = new FieloPLT__Program__c(Name = 'test');
		insert program2;
		FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
		insert member;
		FieloPLT__Member__c member2 = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program2.Id, FieloPLT__User__c = UserInfo.getUserId());
		insert member2;
		FieloCMSPLT_MemberService.getCurrentMember(new Set<String>{'Id','Name'});


	}
}