src/objects/FieloCMS__Category__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Component__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__ComponentLibrary__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Component Library</label>
        <referenceTo>FieloCMS__ComponentLibrary__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__DetailParameter__c</fullName>
        <defaultValue>&apos;id&apos;</defaultValue>
        <description>The name of the parameter that a list will use to send to a detail component</description>
        <label>Detail parameter</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieloCMS__FieldSet__c</fullName>
        <label>FieldSet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Limit__c</fullName>
        <defaultValue>6</defaultValue>
        <inlineHelpText>Set the number of items to show per page</inlineHelpText>
        <label>Items per Page</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloCMS__OrderBy__c</fullName>
        <description>Used on the Catalogo Component to give to the user the option to order the rewards</description>
        <label>Order By</label>
        <picklist>
            <picklistValues>
                <fullName>Name ASC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloCMS__RecordId__c</fullName>
        <description>This field will be used just in memory, containing temporarily the Id of the record that the detail is going to be shown.</description>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tag</label>
        <referenceTo>FieloCMS__Tag__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__ComponentLibrary__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__RecordType__c</fullName>
        <label>Component Type</label>
        <picklist>
            <picklistValues>
                <fullName>List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widget</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Component Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Media__c.object
<CustomObject>
    <description>Media is a repository to show image files.</description>
    <fields>
        <fullName>FieloCMS__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Category to apply to the Media element.</description>
        <inlineHelpText>Choose a Category to apply to the Media element.</inlineHelpText>
        <label>Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Media</relationshipLabel>
        <relationshipName>Media</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media</label>
    <nameField>
        <label>Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Tag__c.object
<CustomObject>
    
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_MediaAPI.cls
/**
* @description
*/
global with sharing class FieloCMSPLT_MediaAPI implements FieloCMS.DataInterface{

    /**
    * @brief Method to get the data on execution
    * @param List<FieloCMS__Component__c> components
    * @return Map<Id, List<sObject>>
    **/
    global Map<Id, Object> getBulkData(List<FieloCMS__Component__c> components){


        Map<Id,Object> newMapData = new Map<Id,Object>();

        Set<String> fieldSet = new Set<String>();
        Map<Id, Id> mapComponentRecord = new Map<Id, Id>();
        for(FieloCMS__Component__c c : components) {
            if(c.FieloCMS__ComponentLibrary__r.FieloCMS__RecordType__c == 'List'){
                newMapData.put(c.Id, FieloCMSPLT_MediaService.getMedia(FieloCMSPLT_OrganizationUtil.getFieldSet(c.FieloCMS__FieldSet__c), c.FieloCMS__Tag__c, c.FieloCMS__Limit__c.intValue(), 0, c.FieloCMS__OrderBy__c, FieloCMSPLT_MemberService.getCurrentMemberId()));
            } else if(c.FieloCMS__ComponentLibrary__r.FieloCMS__RecordType__c == 'Record') {
                fieldSet.addAll( FieloCMSPLT_OrganizationUtil.getFieldSet(c.FieloCMS__FieldSet__c) );
                if ( String.isBlank(c.FieloCMS__RecordId__c) ) {
                    mapComponentRecord.put( c.Id , ApexPages.CurrentPage().getParameters().get( c.FieloCMS__DetailParameter__c ) );
                } else {
                    mapComponentRecord.put( c.Id , c.FieloCMS__RecordId__c );
                }
            }
        }
        if ( !mapComponentRecord.isEmpty() ) {
            List<Id> records = mapComponentRecord.values();
            String query = 'SELECT ' + String.join( new List<String>(fieldSet) ,',') + ' FROM FieloCMS__Media__c WHERE Id IN :records ' ;
            Map<Id,SObject> mapRecords = new Map<Id,SObject>( Database.query( query ) );
            for(Id compId : mapComponentRecord.keySet() ) {
                newMapData.put( compId, mapRecords.get( mapComponentRecord.get(compId) ) );
            }
        }

        System.debug(newMapData);

        return newMapData;
    }

    global List<sObject> getData(FieloCMS__Component__c component, Integer pageNumber, String orderBy, String filters){

        List<SObject> newData = new List<SObject>();
        String categoryId;
        String tagId;
        if(filters != null){
            Map<String,Object> filtersMap = (Map<String,Object>) JSON.deserializeUntyped(filters);
            for(String s : filtersMap.keySet()){
                if(s == 'FieloCMS__Category__c'){
                    categoryId = (String)filtersMap.get(s);
                }else if(s == 'FieloCMS__Tag__c'){
                    tagId = (String)filtersMap.get(s);
                }
            }
        }

        //Prepare all the queries        
        if(component.FieloCMS__Limit__c == null)
            component.FieloCMS__Limit__c = 5;

        //Calculate the offset from the Page Number
        Integer offset = Integer.valueOf(component.FieloCMS__Limit__c * (pageNumber - 1));

        if(categoryId == null && component.FieloCMS__Category__c != null){
            categoryId = component.FieloCMS__Category__c;
        }
        if(tagId == null && component.FieloCMS__Tag__c != null){
            tagId = component.FieloCMS__Tag__c;
        }

        return FieloCMSPLT_MediaService.getMedia(FieloCMSPLT_OrganizationUtil.getFieldSet(component.FieloCMS__FieldSet__c), tagId, component.FieloCMS__Limit__c.intValue(), offset, orderBy, FieloCMSPLT_MemberService.getCurrentMemberId());
    }
}