src/objects/FieloCMS__Component__c.object
<CustomObject>
    <fields>
        <fullName>AccountCRMMode__c</fullName>
        <description>Person Account: Create a new Person Account related to the member
Standard Account: Create a new Standard CRM Account related to the member
Default Account: The member will be related to an specific default CRM account</description>
        <inlineHelpText>Select the behavior about the CRM account for the registration when the contact doesn&apos;t exist or the contact doesn&apos;t have a related CRM account</inlineHelpText>
        <label>Account CRM Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Person Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AccountOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To create CRM account, it is needed a defined user with role as a owner</description>
        <inlineHelpText>Select the owner of the new CRM account created by the component Register</inlineHelpText>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Components2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Components.cls
public without sharing class Components extends SObjectDomain {

    public Components(List<FieloCMS__Component__c> records) {
        super(records);
    }

    public override void onApplyDefaults() {
        List<User> users = [SELECT UserRole.Name, profile.name FROM User where UserRole.Name != null AND profile.Name = 'System Administrator' limit 1];
        List<FieloPLT__Program__c> programs = [SELECT Id, name, CreatedDate FROM FieloPLT__Program__c order by CreatedDate ASC limit 1];
        for(FieloCMS__Component__c record : (List<FieloCMS__Component__c>) records){
            if( record.AccountCRMMode__c == null || record.AccountCRMMode__c == '' ){
                record.AccountCRMMode__c = 'Standard Account';
            }
            //Owner -> Admin con Role
            if(record.AccountOwner__c == null ){
               record.AccountOwner__c = users.get(0).Id;
            }
            //Program -> el primer program creado
            if(record.Program__c == null ){
                record.Program__c = programs.get(0).Id;
            }
        }
    }

    public override void onBeforeInsert() {
    }

    public override void onBeforeUpdate(Map<Id,SObject> existingRecords) {

    }

    public class Constructor implements SObjectDomain.IConstructable {
        public SObjectDomain construct(List<SObject> sObjectList) {
            return new Components(sObjectList);
        }
    }
}