src/objects/FieloCMS__Post__c.object
<CustomObject>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segment</label>
        <referenceTo>FieloPLT__Segment__c</referenceTo>
        <relationshipLabel>Posts</relationshipLabel>
        <relationshipName>Posts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/FieloPLT__Segment__c.object
<CustomObject>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
</CustomObject>

src/classes/SegmentsSelectionControllerTest.cls
@isTest
private class SegmentsSelectionControllerTest {
	
	@isTest static void test_method_one() {
		Id publicId = [select id, name, sobjecttype from recordtype where name = 'Public' limit 1].Id;
		Id manualId = [select id, name, sobjecttype from recordtype where name = 'Manual' limit 1].Id;

		insert new FieloPLT__Segment__c(Name = 'Public', recordtypeId = publicId );
		FieloPLT__Segment__c segment = new FieloPLT__Segment__c(Name = 'Manual', recordtypeId = manualId );
		insert segment;

		FieloPLT__Segment__c segment2 = new FieloPLT__Segment__c(Name = 'Manual2', recordtypeId = manualId );
		insert segment2;

		FieloCMS__Post__c post = new FieloCMS__Post__c(Name = 'test', Segment__c = segment.Id);
		insert post;
		ApexPages.currentPage().getParameters().put('id', post.Id);

		SegmentsSelectionController sgc = new SegmentsSelectionController();


		sgc.addSelected();

		sgc.save();

		sgc.cancel();

		sgc.saveAndExit();

		sgc.getRecordName();

		sgc.getObjectLabel();
		
		sgc.remove();

	}
	
}