src/objects/FieloCMS__Category__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Post__c.object
<CustomObject>
</CustomObject>

src/objects/FieloCMS__Tag__c.object
<CustomObject>
    
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Segment__c.object
<CustomObject>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
</CustomObject>

src/classes/FieloCMSPLT_PostServiceTest.cls
@isTest
private class FieloCMSPLT_PostServiceTest {
	
	@isTest static void test_method_one() {
		FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
		insert program;
		FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
		insert member;


		Id publicId = [select id, name, sobjecttype from recordtype where name = 'Public' limit 1].Id;
		Id privateId = [select id, name, sobjecttype from recordtype where name = 'Private' limit 1].Id;

		insert new FieloPLT__Segment__c(Name = 'Public', recordtypeId = publicId );
		insert new FieloPLT__Segment__c(Name = 'Private', recordtypeId = privateId );

		FieloCMS__Category__c category = new FieloCMS__Category__c(Name = 'Test');
		insert category;

		insert new FieloCMS__Post__c(Name = 'test');

		Set<String> fields = new Set<String>{'Id','Name'};		
		String status = '';
		Id tagId = null;
		Id categoryId = null;
		Integer quantity = 10; 
		Integer offset = 1; 
		String orderBy = 'Name';
		Id memberId = null;

		try{
			FieloCMSPLT_PostService.getPosts(fields, status, tagId, category.Id, quantity, offset, orderBy, memberId);
		}catch(exception e){}
	}

	@isTest static void test_method_two() {
		FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
		insert program;
		FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
		insert member;

		Id publicId = [select id, name, sobjecttype from recordtype where name = 'Public' limit 1].Id;
		Id privateId = [select id, name, sobjecttype from recordtype where name = 'Private' limit 1].Id;

		insert new FieloPLT__Segment__c(Name = 'Public', recordtypeId = publicId );
		insert new FieloPLT__Segment__c(Name = 'Private', recordtypeId = privateId );

		FieloCMS__Category__c category = new FieloCMS__Category__c(Name = 'Test');
		insert category;

		FieloCMS__Tag__c tag = new FieloCMS__Tag__c(Name = 'test');
		insert tag;

		insert new FieloCMS__Post__c(Name = 'test');

		Set<String> fields = new Set<String>{'Id','Name'};		
		String status = '';
		Integer quantity = 10; 
		Integer offset = 1; 
		String orderBy = 'Name';
		Id memberId = null;

		try{
			FieloCMSPLT_PostService.getPosts(fields, status, tag.Id, category.Id, quantity, offset, orderBy, memberId);
		}catch(exception e){}
	}
	
}