src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Points__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Member&apos;s points.</description>
        <inlineHelpText>Member&apos;s points.</inlineHelpText>
        <label>Points</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <fields>
        <fullName>FieloPLT__RequestRedemptionAuthorization__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, new Redemptions need to be approved beforehand.</description>
        <inlineHelpText>When ticked, new Redemptions need to be approved beforehand.</inlineHelpText>
        <label>Request Redemption Authorization</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Reward__c.object
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <fields>
        <fullName>FieloPLT__Points__c</fullName>
        <description>Number of points needed by Rewards to be redeemed.</description>
        <inlineHelpText>Number of points needed by Rewards to be redeemed.</inlineHelpText>
        <label>Points</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Reward belongs to.</description>
        <inlineHelpText>Choose the Program where the Reward belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_CheckoutCtrlTest.cls
@isTest
private class FieloCMSPLT_CheckoutCtrlTest {

    static testMethod void checkout1(){
        FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
        insert program;
        FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
        insert member;

        member.FieloPLT__Points__c = 500;
        FieloPLT.SObjectService.enableAdminPermission(true);
        update member;
        FieloPLT.SObjectService.enableAdminPermission(false);
        
        FieloPLT__Reward__c reward = FieloCMSPLT_MockUpFactory.createRewards('Test', 10, program.Id, 10)[0];
        insert reward;
        Map<Id, Integer> quantityPerReward = new Map<Id, Integer>{reward.Id => 1};
        
        FieloCMSPLT_CheckoutCtrl controller = new FieloCMSPLT_CheckoutCtrl();
        FieloCMSPLT_CheckoutCtrl.checkout(reward.Id,1,'www.fielo.com');
        
    }
   
    static testMethod void checkout2(){
        FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test',FieloPLT__RequestRedemptionAuthorization__c = true);
        insert program;
        FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
        insert member;

        member.FieloPLT__Points__c = 500;
        FieloPLT.SObjectService.enableAdminPermission(true);
        update member;
        FieloPLT.SObjectService.enableAdminPermission(false);
        
        FieloPLT__Reward__c reward = FieloCMSPLT_MockUpFactory.createRewards('Test', 10, program.Id, 10)[0];
        insert reward;
        Map<Id, Integer> quantityPerReward = new Map<Id, Integer>{reward.Id => 1};
        
        FieloCMSPLT_CheckoutCtrl controller = new FieloCMSPLT_CheckoutCtrl();
        FieloCMSPLT_CheckoutCtrl.checkout(reward.Id,1,'www.fielo.com');
        
    }   

    static testMethod void checkout3(){
        FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test',FieloPLT__RequestRedemptionAuthorization__c = true);
        insert program;
        FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
        insert member;

        member.FieloPLT__Points__c = 500;
        FieloPLT.SObjectService.enableAdminPermission(true);
        update member;
        FieloPLT.SObjectService.enableAdminPermission(false);
        
        FieloPLT__Reward__c reward = FieloCMSPLT_MockUpFactory.createRewards('Test', 10, program.Id, 10)[0];
        insert reward;
        Map<Id, Integer> quantityPerReward = new Map<Id, Integer>{member.Id => 1};
        
        FieloCMSPLT_CheckoutCtrl controller = new FieloCMSPLT_CheckoutCtrl();
        FieloCMSPLT_CheckoutCtrl.checkout(reward.Id,1,'www.fielo.com');
        
    }
   
   
}