src/objects/FieloCMS__Category__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Items__c</fullName>
        <label>Items</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Media__c.object
<CustomObject>
    <description>Media is a repository to show image files.</description>
    <fields>
        <fullName>FieloCMS__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Category to apply to the Media element.</description>
        <inlineHelpText>Choose a Category to apply to the Media element.</inlineHelpText>
        <label>Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Media</relationshipLabel>
        <relationshipName>Media</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media</label>
    <nameField>
        <label>Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Tag__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Items__c</fullName>
        <label>Items</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__TagItem__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Media__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media</label>
        <referenceTo>FieloCMS__Media__c</referenceTo>
        <relationshipLabel>Tag Items</relationshipLabel>
        <relationshipName>Tag_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Tag__c</fullName>
        <label>Tag</label>
        <referenceTo>FieloCMS__Tag__c</referenceTo>
        <relationshipLabel>Tag Items</relationshipLabel>
        <relationshipName>Tag_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    
    <label>Tag Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Tag Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Segment__c.object
<CustomObject>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
</CustomObject>

src/classes/FieloCMSPLT_MediaServiceTest.cls
@isTest
private class FieloCMSPLT_MediaServiceTest
{
  @isTest
  static void itShould()
  {
    Fielo_SObjectForTest.setAbbreviation();
    
    Account lAccount = Fielo_SObjectForTest.getAccount();
    insert lAccount;

        FieloCMSPLT_MockupFactory.setProgramAndMember();
        
        FieloPLT__Program__c lProgram = [SELECT Id FROM FieloPLT__Program__c];
        
        FieloPLT__Member__c lMember = [SELECT Id FROM FieloPLT__Member__c];

    FieloCMS__Tag__c lTag = new FieloCMS__Tag__c();
    lTag.Name = 'Test';
    lTag.FieloCMS__Items__c = 1;
    insert lTag;

    RecordType lRT = [SELECT id, DeveloperName FROM RecordType WHERE DeveloperName = 'Private' limit 1];
    FieloPLT__Segment__c lSegment = new FieloPLT__Segment__c();
    lSegment.RecordTypeId = lRT.id;
    insert lSegment;

    System.debug('## = ' + lSegment.RecordType +' <lSegment-SELECT> '+ [SELECT Id FROM FieloPLT__Segment__c WHERE RecordType.DeveloperName = 'Private' LIMIT 1]);

    Set<String> lFields = new Set<String>();
    lFields.add('Name');

    FieloCMS__Category__c lCategory = new FieloCMS__Category__c();
    insert lCategory;

    FieloCMS__Media__c lMedia = new FieloCMS__Media__c();
    lMedia.FieloCMS__Category__c = lCategory.id;
    insert lMedia;

    FieloCMS__TagItem__c lTagItem = new FieloCMS__TagItem__c();
    lTagItem.FieloCMS__Tag__c = lTag.id;
    lTagItem.FieloCMS__Media__c = lMedia.id;
    insert lTagItem;

    FieloCMSPLT_MediaService.getMedia(lFields, lTag.id, lCategory.id, 1, 1, 'id', lMember.id, null);
  }

  @isTest
  static void itShould2()
  {
    Fielo_SObjectForTest.setAbbreviation();
    
    Account lAccount = Fielo_SObjectForTest.getAccount();
    insert lAccount;

        FieloCMSPLT_MockupFactory.setProgramAndMember();
        
        FieloPLT__Program__c lProgram = [SELECT Id FROM FieloPLT__Program__c];
        
        FieloPLT__Member__c lMember = [SELECT Id FROM FieloPLT__Member__c];

    FieloCMS__Tag__c lTag = new FieloCMS__Tag__c();
    lTag.Name = 'Test';
    lTag.FieloCMS__Items__c = 1;
    insert lTag;

    RecordType lRT = [SELECT id, DeveloperName FROM RecordType WHERE DeveloperName = 'Private' limit 1];
    FieloPLT__Segment__c lSegment = new FieloPLT__Segment__c();
    lSegment.RecordTypeId = lRT.id;
    insert lSegment;

    System.debug('## = ' + lSegment.RecordType +' <lSegment-SELECT> '+ [SELECT Id FROM FieloPLT__Segment__c WHERE RecordType.DeveloperName = 'Private' LIMIT 1]);

    Set<String> lFields = new Set<String>();
    lFields.add('Name');

    FieloCMS__Category__c lCategory = new FieloCMS__Category__c();
    insert lCategory;

    FieloCMS__Media__c lMedia = new FieloCMS__Media__c();
    lMedia.FieloCMS__Category__c = lCategory.id;
    insert lMedia;

    FieloCMS__TagItem__c lTagItem = new FieloCMS__TagItem__c();
    lTagItem.FieloCMS__Tag__c = lTag.id;
    lTagItem.FieloCMS__Media__c = lMedia.id;
    insert lTagItem;

    FieloCMSPLT_MediaService.getMedia(lFields, null, lCategory.id, 1, 1, 'id', lMember.id, null);
  }
}