src/objects/FieloCMS__Component__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__ComponentLibrary__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Component Library</label>
        <referenceTo>FieloCMS__ComponentLibrary__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__DetailView__c</fullName>
        <description>This field will determine how the detail an item from a list is displayed.</description>
        <label>Detail view</label>
        <picklist>
            <controllingField>FieloCMS__Layout__c</controllingField>
            <picklistValues>
                <fullName>Internal page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accordion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Page__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + FieloCMS__Section__r.FieloCMS__Parent__r.FieloCMS__Page__c, FieloCMS__Section__r.FieloCMS__Parent__r.FieloCMS__Page__r.Name, &apos;_self&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Page</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Section to which the component belongs</description>
        <label>Section</label>
        <referenceTo>FieloCMS__Section__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__ComponentLibrary__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Plugin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plugin</label>
        <referenceTo>FieloCMS__Plugin__c</referenceTo>
        <relationshipLabel>Components Library</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Page__c.object
<CustomObject>
    <description>The members’ portal&apos;s pages and templates</description>
    <fields>
        <fullName>FieloCMS__Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>FieloCMS__Site__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Menu</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Plugin__c.object
<CustomObject>
    <label>Plugin</label>
    <nameField>
        <label>Plugin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plugin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Section__c.object
<CustomObject>
    <description>A Section is an area within Pages and Templates which include Subsections.</description>
    <fields>
        <fullName>FieloCMS__Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Page/Template where the Section belongs to.</description>
        <label>Page</label>
        <referenceTo>FieloCMS__Page__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Section where a subsection belongs to.</description>
        <label>Parent</label>
        <referenceTo>FieloCMS__Section__c</referenceTo>
        <relationshipLabel>Sections</relationshipLabel>
        <relationshipName>Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Site__c.object
<CustomObject>
    <description>A Fielo Site is a content and structure administrator for multiple Salesforce Sites.</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Reward__c.object
<CustomObject>
    <description>Rewards are the prizes available to Members who are part of a Program.</description>
    <fields>
        <fullName>FieloPLT__Points__c</fullName>
        <description>Number of points needed by Rewards to be redeemed.</description>
        <inlineHelpText>Number of points needed by Rewards to be redeemed.</inlineHelpText>
        <label>Points</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Reward belongs to.</description>
        <inlineHelpText>Choose the Program where the Reward belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Rewards</relationshipLabel>
        <relationshipName>Rewards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Stock__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Reward items available to be redeem.</description>
        <inlineHelpText>Reward items available to be redeem.</inlineHelpText>
        <label>Items Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_OrganizationUtilTest.cls
@isTest
private class FieloCMSPLT_OrganizationUtilTest{

	@isTest
	static void test1(){
		String fieldSet = '';
		FieloCMSPLT_OrganizationUtil.getFieldSet(fieldSet);

		FieloCMSPLT_OrganizationUtil.isPersonAccountEnabled();
	}

	@isTest
	static void insertMethods(){
		/*FieloCMS__Plugin__c plugin1 = new FieloCMS__Plugin__c( Name = 'Default', FieloCMS__Resource__c = 'www.url.com/static1', FieloCMS__ResourceContent__c = 'CSS' );
        insert new List<FieloCMS__Plugin__c> { plugin1};

        FieloCMS__ComponentLibrary__c componentLibrary1 = new FieloCMS__ComponentLibrary__c( Name = 'Default', FieloCMS__Plugin__c = plugin1.Id );
        insert new List<FieloCMS__ComponentLibrary__c> { componentLibrary1 };

    	//Crea una Pagina con un componente del plugin 1
        FieloCMS__Site__c site = new FieloCMS__Site__c(Name = 'Default');
        insert site;

        FieloCMS__Page__c page =  new FieloCMS__Page__c( Name = 'Default', FieloCMS__Site__c = site.Id);
        insert page;

        FieloCMS__Section__c section = new FieloCMS__Section__c(  FieloCMS__Page__c = page.Id);
        insert section;

        FieloCMS__Section__c subsection = new FieloCMS__Section__c( FieloCMS__Parent__c = section.Id);
        insert subsection;

        FieloCMS__Component__c component1 = new FieloCMS__Component__c( Name = 'Default', FieloCMS__Section__c = subsection.Id, FieloCMS__ComponentLibrary__c = componentLibrary1.id, FieloCMS__DetailView__c = 'Modal' );
        insert component1;


        insert new FieloPLT__Program__c(Name = 'test');

        insert new FieloPLT__Reward__c(Name = 'test', FieloPLT__Points__c = 10, FieloPLT__Stock__c = 10);*/
	}
	
	@isTest
	static void itShould(){
/*
		OrganizationUtil.temporalTest1();
		OrganizationUtil.temporalTest2();
		OrganizationUtil.temporalTest3();
		OrganizationUtil.temporalTest4();
		OrganizationUtil.temporalTest5();
		OrganizationUtil.temporalTest6();
		OrganizationUtil.temporalTest7();
		OrganizationUtil.temporalTest8();
		OrganizationUtil.temporalTest9();
		OrganizationUtil.temporalTest10();
		OrganizationUtil.temporalTest11();
		OrganizationUtil.temporalTest12();
		OrganizationUtil.temporalTest13();
		OrganizationUtil.temporalTest14();
		OrganizationUtil.temporalTest15();
		OrganizationUtil.temporalTest16();
		OrganizationUtil.temporalTest17();
		OrganizationUtil.temporalTest18();
		OrganizationUtil.temporalTest19();
		OrganizationUtil.temporalTest20();
		OrganizationUtil.temporalTest21();
		OrganizationUtil.temporalTest22();
		OrganizationUtil.temporalTest23();
		OrganizationUtil.temporalTest24();
		OrganizationUtil.temporalTest25();
		OrganizationUtil.temporalTest26();
		OrganizationUtil.temporalTest27();
		OrganizationUtil.temporalTest28();
		OrganizationUtil.temporalTest29();
		OrganizationUtil.temporalTest30();*/

	}
}