src/objects/FieloCMS__Plugin__c.object
<CustomObject>
    <label>Plugin</label>
    <nameField>
        <label>Plugin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plugin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Site__c.object
<CustomObject>
    <description>A Fielo Site is a content and structure administrator for multiple Salesforce Sites.</description>
    <fields>
        <fullName>FieloCMS__PluginCSS__c</fullName>
        <label>Plugin&apos;s CSS</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieloCMS__PluginJS__c</fullName>
        <label>Plugin&apos;s Javascript</label>
        <length>1200</length>
        <type>LongTextArea</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_Plugins.cls
public class FieloCMSPLT_Plugins extends FieloCMSPLT_SObjectDomain {
	
	public FieloCMSPLT_Plugins(List<FieloCMS__Plugin__c> records){
		super(records);	
	}

	public override void onApplyDefaults(){
	}

	public override void onValidate(){
		for(FieloCMS__Plugin__c record : (List<FieloCMS__Plugin__c>) records){
		}
	}

	public override void onValidate(Map<Id,SObject> existingrecords){
		for(FieloCMS__Plugin__c record : (List<FieloCMS__Plugin__c>) records){
		}
	}

	public override void onBeforeInsert(){
		loadCSSJS();
	}

	public override void onBeforeUpdate(Map<Id,SObject> existingrecords){
		loadCSSJS();
	}

	//for every site, put the CSS and JS information taking into account the static resources
	private static void loadCSSJS(){
		//query all static resources whose name starts with FieloPlugin_
		List<StaticResource> resourceList = [SELECT Name, NamespacePrefix, SystemModStamp FROM StaticResource WHERE Name Like 'FieloPlugin_%'];

		List<FieloCMS__Site__c> sites = new FieloCMSPLT_SitesSelector(new Set<String>{'Id'}).selectAll();
		//limpio
		for(FieloCMS__Site__c site : sites){
			site.FieloCMS__PluginCSS__c = '';
			site.FieloCMS__PluginJS__c = '';
		}

		for(FieloCMS__Site__c site : sites){
			for(StaticResource sr : resourceList){
				String urlSR = getResourceURL(sr);
				site.FieloCMS__PluginCSS__c += urlSR + '\n';
				site.FieloCMS__PluginJS__c += urlSR + '\n';		
			}
		}
		FieloCMSPLT_SObjectUnitOfWork uow = new FieloCMSPLT_SObjectUnitOfWork(new List<Schema.SobjectType>{FieloCMS__Site__c.SObjectType});
		uow.registerDirty(sites);
		uow.commitWork();
	}

	// Pass the resource name
	public static String getResourceURL(StaticResource resource){

		// Getting namespace
		String namespace = resource.NamespacePrefix;
		// Resource URL
		return '/resource/' + resource.SystemModStamp.getTime() + '/' + (String.isNotBlank(namespace) ? namespace + '__' : '') + resource.Name; 
	}

	public class Constructor implements FieloCMSPLT_SObjectDomain.IConstructable{
		
		public FieloCMSPLT_SObjectDomain construct(List<SObject> sObjectList){
			return new FieloCMSPLT_Plugins(sObjectList);
		}
	}	
}