src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Member&apos;s status.</description>
        <inlineHelpText>Member&apos;s status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_LoginService.cls
public class FieloCMSPLT_LoginService {

    public static Pagereference login(String userName, String password, String startUrl){
        username = username.trim();
        try{
            //Checks if the user is inactive and activate it, after that redirects to the page to reactivate the user
            List<User> inactiveUsers = [SELECT Username, Name, IsActive, Id, Email From User where IsActive = false AND Username =: username limit 1];
            if(inactiveUsers.size() > 0){
                inactiveUsers.get(0).IsActive = true;
                update inactiveUsers;
            }
        }catch(exception e){
            throw new FieloCMSPLT_Exception(e.getMessage());
        }

        FieloPLT__Program__c program = FieloCMSPLT_ProgramService.getCurrentProgram();
        //look for the member related to the username
        List<FieloPLT__Member__c> membersByEmail = [SELECT FieloPLT__Status__c, FieloPLT__User__c, FieloPLT__Program__r.FieloCMSPLT_UseAgreement__c FROM FieloPLT__Member__c WHERE FieloPLT__Email__c =: username AND FieloPLT__Program__c =: program.Id];

        //if the member was not found throws an error
        if(membersByEmail.isEmpty()){
            throw new FieloCMSPLT_Exception(Label.FieloCMSPLT_ErrorLoginProgramValidation);
        }

        //if the member was found but is blocked thtrows an error
        if(membersByEmail.get(0).FieloPLT__Status__c == 'Blocked'){
            throw new FieloCMSPLT_Exception(Label.FieloCMSPLT_ErrorLoginMemberBlocked);
        }

        /*
        //check selection member page
        if(membersByEmail.get(0).FieloPLT__User__c != null){
            List<FieloPLT__Member__c> relatedMembers = new MembersSelector().selectRelatedMembers(UserInfo.getUserId(), program.Id);
            if(relatedMembers.size() > 1 && String.isNotBlank(program.FieloCMSPLT_MemberSelectionPage__c)){
                PageReference selectionPage = new PageReference('/FieloCMS__Page');
                selectionPage.getParameters().put('pageId',program.FieloCMSPLT_MemberSelectionPage__c);
                startUrl = selectionPage.getUrl();
            }
        }*/

        
        //login
        return Site.login(username, password, startUrl);
    }

    public static PageReference forgotPassword(String userName){
        //Validates if the userName is not empty
        if(String.isBlank(username)){
            throw new FieloCMSPLT_Exception(Label.FieloCMSPLT_UsernameIsRequired);
            return null;
        }
        //looks if the user is inactive and then activates the user
        List<User> user = [SELECT Username, Name, IsActive, Id, Email FROM User WHERE Username =: username LIMIT 1];

        //if the user was found and is inactive then is activated and updated
        if(user.size() > 0){
            if(user.get(0).IsActive == false){
                user.get(0).IsActive = true;
                update user;
            }
        //if the user does not exist an error is returned
        }else{
            throw new FieloCMSPLT_Exception(Label.FieloCMSPLT_ErrorMemberForgotPasswordInexist);
        }

        Site.forgotPassword(username);

        return null;
    }
}