src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SessionCache__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <label>Session Cache</label>
</CustomObject>

src/classes/FieloCMSPLT_LoginAsCtrlTest.cls
@isTest
private class FieloCMSPLT_LoginAsCtrlTest {

    @isTest static void validLogin() {
        //comentado porque ahora 
        //crate new member with user
        // FieloCMSPLT_MockUpFactory.setCustomProperties(false);
		Profile p = [select id, name, UserType, UserLicense.Name from profile where UserType = 'Standard' limit 1];
	    User u = new User(Alias = 'standt', Email='test@fielo.com', EmailEncodingKey='UTF-8', LastName='Testing',LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='plugintest@fielo.com', isActive = true);
	    insert u;

        FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
        insert program;

        FieloPLT__Member__c member = new FieloPLT__Member__c( Name = 'test member', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.id, FieloPLT__User__c = u.id);
        insert member;

        //get custom setting and set a valid hash and expiration date
        SessionCache__c fe = SessionCache__c.getInstance(u.Id);
        fe.FieloCMSPLT_Hash__c = 'testHash';
        fe.FieloCMSPLT_ExpirationDate__c = System.now().addMinutes(5);
        upsert fe;

        FieloCMSPLT_LoginAsCtrl controller = new FieloCMSPLT_LoginAsCtrl();
        system.currentPageReference().getParameters().put('testUser',u.Id);
        system.currentPageReference().getParameters().put('hash','testHash');
        controller.login();
    }

    @isTest static void invalidLogin() {
        //comentado porque ahora el usuario se crea por front end
        //crate new member with user
        //FieloCMSPLT_MockUpFactory.setCustomProperties(false);
		Profile p = [select id, name, UserType, UserLicense.Name from profile where UserType = 'Standard' limit 1];
	    User u = new User(Alias = 'standt', Email='test@fielo.com', EmailEncodingKey='UTF-8', LastName='Testing',LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='plugintest@fielo.com', isActive = true);
	    insert u;

        FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
        insert program;

        FieloPLT__Member__c member = new FieloPLT__Member__c( Name = 'test member', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.id, FieloPLT__User__c = u.id);
        insert member;

        FieloCMSPLT_LoginAsCtrl controller = new FieloCMSPLT_LoginAsCtrl();
        system.currentPageReference().getParameters().put('testUser',u.Id);     
        controller.login();
    }
    
}