src/objects/FieloCMS__Category__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Component__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>FieloCMS__Category__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__ComponentLibrary__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Component Library</label>
        <referenceTo>FieloCMS__ComponentLibrary__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__DetailView__c</fullName>
        <description>This field will determine how the detail an item from a list is displayed.</description>
        <label>Detail view</label>
        <picklist>
            <controllingField>FieloCMS__Layout__c</controllingField>
            <picklistValues>
                <fullName>Internal page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accordion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloCMS__FieldSet__c</fullName>
        <label>FieldSet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Section to which the component belongs</description>
        <label>Section</label>
        <referenceTo>FieloCMS__Section__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tag</label>
        <referenceTo>FieloCMS__Tag__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__ComponentLibrary__c.object
<CustomObject>
    <label>Component Library</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Section__c.object
<CustomObject>
    <description>A Section is an area within Pages and Templates which include Subsections.</description>
    <label>Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Tag__c.object
<CustomObject>
    
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_RewardAPITest.cls
@isTest
private class FieloCMSPLT_RewardAPITest{

    @isTest
    static void testGetBulk(){
        Id programId = FieloCMSPLT_MockupFactory.createProgram();
        Id memberId = FieloCMSPLT_MockupFactory.createMember('TestMember', 'testMail@fielo.com', programId, UserInfo.getUserId());
        
        Id componentLibraryId = FieloCMSPLT_MockupFactory.createComponentLibrary();
        Id subsectionId = FieloCMSPLT_MockupFactory.createMenuSection();
    
        FieloCMS__Tag__c tag = new FieloCMS__Tag__c(Name = 'Default');
        insert tag;
        FieloCMS__Category__c cat = new FieloCMS__Category__c(Name = 'Default');
        insert cat;
        
        FieloCMS__Component__c component1 = new FieloCMS__Component__c( Name = 'Default', FieloCMS__Section__c = subsectionId, FieloCMS__ComponentLibrary__c = componentLibraryId, FieloCMS__DetailView__c = 'Modal', FieloCMS__Tag__c = tag.Id, FieloCMS__Category__c = cat.Id );
        component1.FieloCMS__FieldSet__c= '[{"showLabel":true,"label":"Code","apiName":"Name","type":"STRING"}]';        
        insert component1;
        
        FieloCMSPLT_RewardAPI c = new FieloCMSPLT_RewardApi();
        c.getBulkData( new List<FieloCMS__Component__c> { component1 } );
        c.getData( component1 , 0, null, null );
    }
    
}