src/objects/FieloPLT__Agreement__c.object
<CustomObject>
    <description>Terms and conditions of service that Members need to accept in order to be part of the loyalty Program in which you wish to include them.</description>
    <fields>
        <fullName>FieloPLT__Agreement__c</fullName>
        <description>Agreement terms and conditions.</description>
        <inlineHelpText>Enter the Agreement terms and conditions.</inlineHelpText>
        <label>Agreement</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program which the Agreement belongs to.</description>
        <inlineHelpText>Choose Program which the Agreement belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Agreement status: Draft, Current, Active or Deprecated.</description>
        <inlineHelpText>Agreement status. Only one Agreement be active.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Version</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_AgreementsSelector.cls
public class FieloCMSPLT_AgreementsSelector extends FieloCMSPLT_SObjectSelector{
	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField> {
				FieloPLT__Agreement__c.Id
			};
	}

	public FieloCMSPLT_AgreementsSelector(Set<String> fields){
		super(fields);
	}

	public FieloCMSPLT_AgreementsSelector(){
        super();
    }

	public Schema.SObjectType getSObjectType(){
		return FieloPLT__Agreement__c.sObjectType;
	}

	public List<FieloPLT__Agreement__c> selectById(Set<ID> idSet){
		return (List<FieloPLT__Agreement__c>) selectSObjectsById(idSet);
	}

	public List<FieloPLT__Agreement__c> selectCurrentByProgram(Id programId){
		String currentStatus = 'Current';
		assertIsAccessible();
		return (List<FieloPLT__Agreement__c>) Database.query(
				String.format(
				'select {0} ' +
				  'from {1} ' +
				  'where FieloPLT__Status__c =: currentStatus AND FieloPLT__Program__c =: programId ' + 
				  'order by {2}',
				new List<String> {
					getFieldListString(),
					getSObjectName(),
					getOrderBy() } ) );
	}

	/*
	 * For more examples see https://github.com/financialforcedev/SegmentCriteria__r-apex-common-samplecode
	 * 
	public List<FieloPLT__Agreement__c> selectBySomethingElse(List<String> somethings){
		assertIsAccessible();
		return (List<FieloPLT__Agreement__c>) Database.query(
				String.format(
				'select {0} ' +
				  'from {1} ' +
				  'where Something__c in :somethings ' + 
				  'order by {2}',
				new List<String> {
					getFieldListString(),
					getSObjectName(),
					getOrderBy() } ) );
	}
	 */
}