src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Salesforce CRM Account name.</description>
        <inlineHelpText>Salesforce CRM Account name.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__OrganizationAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization account linked to the Organization Contributor account.</description>
        <inlineHelpText>Choose Organization account where the Organization Contributor Member belongs to.</inlineHelpText>
        <label>Organization Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Member must be an &quot;Organization Account&quot; and belong to the same Program.</errorMessage>
            <filterItems>
                <field>FieloPLT__Member__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Organization Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Members (Organization Account)</relationshipLabel>
        <relationshipName>FieloAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Member&apos;s status.</description>
        <inlineHelpText>Member&apos;s status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_HandleInvitationsMbrCtrlTest.cls
@isTest
private class FieloCMSPLT_HandleInvitationsMbrCtrlTest {
	
	@isTest static void test_method_one() {
		FieloCMSPLT_MockupFactory.setProgramAndMember();

		FieloPLT__Member__c member = [SElect id, name from FieloPLT__Member__c limit 1];

		FieloCMSPLT_HandleInvitationsMbrCtrl.resendInvitation(member.Id);
		FieloCMSPLT_HandleInvitationsMbrCtrl.cancelInvitation(member.Id);
	}
	
	@isTest static void test_method_two() {
		FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
		insert program;
		Account a = new Account(Name = 'test');
		insert a;
		FieloPLT__Member__c orgaAccount = new FieloPLT__Member__c(Name = 'test', FieloPLT__Account__c = a.Id, FieloPLT__Program__c = program.Id, FieloPLT__Status__c = 'Active', FieloPLT__Email__c = 'test1@fielo.com', FieloPLT__Type__c = 'Organization Account');
		insert orgaAccount;
		FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId(), FieloPLT__OrganizationAccount__c = orgaAccount.Id, FieloPLT__Type__c = 'Organization Contributor');
		insert member;

		


		FieloCMSPLT_HandleInvitationsMbrCtrl.cancelInvitation(member.Id);
	}
	
}