src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <fields>
        <fullName>SiteDomain__c</fullName>
        <label>Site Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteURL__c</fullName>
        <description>The URL used to complete the registration process.</description>
        <inlineHelpText>URL of the site used to send the links to continue the registration process</inlineHelpText>
        <label>Site URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Programs.cls
public without sharing class Programs {

    public static void formatSiteDomain(List<FieloPLT__Program__c> programs){
        for(FieloPLT__Program__c p : programs){
            if(p.SiteURL__c != null && p.SiteURL__c != ''){
                p.SiteDomain__c = p.SiteURL__c.replace('http://','').replace('https://','').replace('.secure.','.');
                if(p.SiteURL__c.lastIndexOf('/') != p.SiteURL__c.length()-1) p.SiteURL__c = p.SiteURL__c + '/';
                if(p.SiteDomain__c.lastIndexOf('/') == p.SiteDomain__c.length()-1)
                    p.SiteDomain__c = p.SiteDomain__c.subString(0,p.SiteDomain__c.lastIndexOf('/'));
            }
        }
    }
}