src/objects/FieloCMS__Component__c.object
<CustomObject>
    <fields>
        <fullName>FieloCMS__FieldSet__c</fullName>
        <label>FieldSet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Navigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Navigation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FieloCMS__Navigation__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>List</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FieloCMS__Navigation__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Navigation__c.object
<CustomObject>
    <description>A Navigation allows you to access the created Pages and Content from the Site.</description>
    <fields>
        <fullName>FieloCMS__Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>FieloCMS__Site__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloCMS__Url__c</fullName>
        <description>Build the url using the CustomUrl or the Page&apos;s lookup field</description>
        <formula>IF( !ISBLANK(FieloCMS__CustomURL__c) &amp;&amp; !ISNULL(FieloCMS__CustomURL__c) , FieloCMS__CustomURL__c , IF(!ISBLANK($Setup.FieloCMS__OrganizationSettings__c.FieloCMS__PackagePrefix__c) &amp;&amp; !ISNULL($Setup.FieloCMS__OrganizationSettings__c.FieloCMS__PackagePrefix__c), &apos;/&apos; + $Setup.FieloCMS__OrganizationSettings__c.FieloCMS__PackagePrefix__c + &apos;__Page?navId=&apos; + Id , &apos;/Page?navId=&apos; + Id))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Url</label>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloCMS__Site__c.object
<CustomObject>
    <description>A Fielo Site is a content and structure administrator for multiple Salesforce Sites.</description>
    <fields>
        <fullName>FieloCMS__SiteId__c</fullName>
        <label>Salesforce Site</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NavigationAPI.cls
global class NavigationAPI implements FieloCMS.DataInterface{

    global Map<Id, Object> getBulkData(List<FieloCMS__Component__c> components){
        Map<Id,Object> newMapData = new Map<Id,Object>();


        String siteId = Site.getSiteId();

        List<FieloCMS__Site__c> sites = [SELECT Id FROM FieloCMS__Site__c WHERE FieloCMS__SiteId__c =: siteId];
        if(!sites.isEmpty()){
            siteId = sites.get(0).Id;
        }                

        //Prepare all the queries
        for(FieloCMS__Component__c c : components){

            //como hay campos que necesito sí o sí traer en el query, me armo un set en low case de los campos
            Set<String> fieldsToQuery = new Set<String>();
            fieldsToQuery.add('fielocms__url__c');

            for(String fieldName : OrganizationUtil.getFieldSet(c.FieloCMS__FieldSet__c)){
                fieldsToQuery.add(fieldName.toLowerCase());
            }

            newMapData.put(c.Id, NavigationService.getNavigations(c.FieloCMS__Navigation__c, fieldsToQuery, siteId, MemberService.getCurrentMemberId(), true));
        }
        return newMapData;
    }

    global List<sObject> getData(FieloCMS__Component__c component, Integer pageNumber, String orderBy, String filters){
        return null;
    }

}