src/objects/FieloAlpha__Program__c.object
<CustomObject>
    <description>Settings of each of your Fielo programs. You can create up to XXXX different programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloAlpha__RedemptionRule__c.object
<CustomObject>
    <customHelpPage>FieloAlpha__RedemptionRuleHelpBackEnd</customHelpPage>
    <description>Arbitrary groups to which members can belong. You can create segments by age, by location, etc.</description>
    <fields>
        <fullName>FieloAlpha__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>FieloAlpha__Program__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloAlpha__SegmentDomain__c.object
<CustomObject>
    <customHelpPage>FieloAlpha__RedemptionRuleHelpBackEnd</customHelpPage>
    <description>Segments that can access a certain object, like a banner, a reward or a content feed.</description>
    <fields>
        <fullName>FieloAlpha__Segment__c</fullName>
        <label>Segment</label>
        <referenceTo>FieloAlpha__RedemptionRule__c</referenceTo>
        <relationshipLabel>Segment Domains</relationshipLabel>
        <relationshipName>SegmentDomain</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Segment Domain</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>SegmentDomain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Domains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCreateUser.cls
@isTest
private class TestCreateUser
{
	@isTest
	static void itShould()
	{
                FieloAlpha__Program__c defaultProgram = new FieloAlpha__Program__c(FieloAlpha__Default__c = true);
                insert defaultProgram;

                FieloAlpha__RedemptionRule__c segment = new FieloAlpha__RedemptionRule__c();
                insert segment;

                insert new FieloAlpha__SegmentDomain__c(FieloAlpha__Segment__c = segment.Id);
		
                OrganizationUtil.dummyTest1();
                OrganizationUtil.dummyTest2();
                OrganizationUtil.dummyTest3();
                OrganizationUtil.dummyTest4();
                OrganizationUtil.dummyTest5();
                OrganizationUtil.dummyTest6();
                OrganizationUtil.dummyTest7();
                OrganizationUtil.dummyTest8();
                OrganizationUtil.dummyTest9();
                OrganizationUtil.dummyTest10();
                OrganizationUtil.dummyTest11();
                OrganizationUtil.dummyTest12();
                OrganizationUtil.dummyTest13();
                OrganizationUtil.dummyTest14();
                OrganizationUtil.dummyTest15();
                OrganizationUtil.dummyTest16();
	}

}