src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Member&apos;s status.</description>
        <inlineHelpText>Member&apos;s status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Redemption__c.object
<CustomObject>
    <description>Redemptions are the orders generated by Members when they redeem their available points for Rewards.</description>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member who performed the Redemption.</description>
        <inlineHelpText>Member who performed the Redemption.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Redemptions</relationshipLabel>
        <relationshipName>Redemptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Origin__c</fullName>
        <description>Source from which the Redemption order was generated.</description>
        <inlineHelpText>Source from which the Redemption order was generated.</inlineHelpText>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>BackEnd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FrontEnd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>The status of this redemption. Possible status values are: Open, Closed, Pending or Rejected.</description>
        <inlineHelpText>Redemption status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Redemption</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redemptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_RedemptionsSelector.cls
public class FieloCMSPLT_RedemptionsSelector extends FieloCMSPLT_SObjectSelector{
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                FieloPLT__Redemption__c.Id
            };
    }

    public FieloCMSPLT_RedemptionsSelector(Set<String> fields){
        super(fields);
    }

    public FieloCMSPLT_RedemptionsSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return FieloPLT__Redemption__c.sObjectType;
    }

    public List<FieloPLT__Redemption__c> selectById(Set<ID> idSet){
        return (List<FieloPLT__Redemption__c>) selectSObjectsById(idSet);
    }

    public List<FieloPLT__Redemption__c> selectByStatusOriginAndMember(String status, String origin, Id memberId){
        assertIsAccessible();
        return (List<FieloPLT__Redemption__c>) Database.query(
                String.format(
                'select {0} ' +
                  'from {1} ' +
                  'where FieloPLT__Status__c =: status AND FieloPLT__Member__c =: memberId AND FieloPLT__Origin__c =: origin ' + 
                  'order by {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ) );
    }

    /*
     * For more examples see https://github.com/financialforcedev/fflib-apex-common-samplecode
     * 
    public List<FieloPLT__Redemption__c> selectBySomethingElse(List<String> somethings)
    {
        assertIsAccessible();
        return (List<FieloPLT__Redemption__c>) Database.query(
                String.format(
                'select {0} ' +
                  'from {1} ' +
                  'where Something__c in :somethings ' + 
                  'order by {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ) );
    }
     */
}