src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_LoginServiceTest.cls
@isTest
private class FieloCMSPLT_LoginServiceTest {
	
	@isTest static void test_method_one() {
		
		FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
		insert program;
		FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'plugintest@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
		insert member;

		//Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
		Profile p = [select id, name, UserType, UserLicense.Name from profile where UserType = 'Standard' limit 1];
		User u = new User(Alias = 'standt', Email='test@fielo.com', EmailEncodingKey='UTF-8', LastName='Testing',LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='plugintest@fielo.com', isActive = false);
		insert u;

		Test.startTest();
			try{
				FieloCMSPLT_LoginService.login('plugintest1@fielo.com', 'qwer1235', 'www.google.com');
			}catch(Exception e){}
			
		Test.stopTest();
		//FieloCMSPLT_LoginService.login('plugintest@fielo.com', 'qwer1235', 'www.google.com');
	}
	
	@isTest static void test_method_two() {

		try{
			FieloCMSPLT_LoginService.forgotPassword('');
		}catch(Exception e){

		}
		
		try{
			FieloCMSPLT_LoginService.forgotPassword('test@fielo.com');
		}catch(Exception e){

		}

        //Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
		Profile p = [select id, name, UserType, UserLicense.Name from profile where UserType = 'Standard' limit 1];
		User u = new User(Alias = 'standt', Email='test@fielo.com', EmailEncodingKey='UTF-8', LastName='Testing',LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='test1plugin@fielo.com');
		insert u;

		FieloCMSPLT_LoginService.forgotPassword('test1plugin@fielo.com');
	}
	
}