src/objects/FieloCMS__Post__c.object
<CustomObject>
</CustomObject>

src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Segment__c.object
<CustomObject>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <label>Private</label>
    </recordTypes>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
</CustomObject>

src/classes/FieloCMSPLT_SegmentsSelectionCtrlTest.cls
@isTest
private class FieloCMSPLT_SegmentsSelectionCtrlTest {
	
	@isTest static void test_method_one() {
		Id publicId = [select id, name, sobjecttype from recordtype where name = 'Public' limit 1].Id;
		Id manualId = [select id, name, sobjecttype from recordtype where name = 'Manual' limit 1].Id;

		insert new FieloPLT__Segment__c(Name = 'Public', recordtypeId = publicId );
		FieloPLT__Segment__c segment = new FieloPLT__Segment__c(Name = 'Manual', recordtypeId = manualId );
		insert segment;

		FieloPLT__Segment__c segment2 = new FieloPLT__Segment__c(Name = 'Manual2', recordtypeId = manualId );
		insert segment2;

		FieloCMS__Post__c post = new FieloCMS__Post__c(Name = 'test', FieloCMSPLT_Segment__c = segment.Id);
		insert post;
		ApexPages.currentPage().getParameters().put('id', post.Id);

		FieloCMSPLT_SegmentsSelectionCtrl sgc = new FieloCMSPLT_SegmentsSelectionCtrl();


		sgc.addSelected();

		sgc.save();

		sgc.cancel();

		sgc.saveAndExit();

		sgc.getRecordName();

		sgc.getObjectLabel();
		
		try{
			apexpages.currentpage().getparameters().put('indexToRemove', '1');
			sgc.remove();
		}catch(Exception e){}


		FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'test');
		insert program;
		FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test', FieloPLT__Email__c = 'test@fielo.com', FieloPLT__Program__c = program.Id, FieloPLT__User__c = UserInfo.getUserId());
		insert member;
		FieloCMSPLT_SegmentsSelectionCtrl.getMetaSegmentId(new List<String>(), program.Id);


		List<String> segmentos = new List<String>();
		segmentos.add(String.valueOf(segment2));
		segmentos.add(String.valueOf(segment));
		FieloCMSPLT_SegmentsSelectionCtrl.getMetaSegmentId(segmentos, program.Id);

	}
	
}