src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_LoginAsBackendCtrlTest.cls
@isTest
private class FieloCMSPLT_LoginAsBackendCtrlTest {

    @isTest(seeAllData=false) static void redirectSuccessful() {

      FieloPLT__Program__c lProgram = new FieloPLT__Program__c(Name = 'test');
        insert lProgram;
        //crate new member with user
        FieloPLT__Member__c member = new FieloPLT__Member__c(Name = 'test member');
        insert member;
                
        FieloCMSPLT_LoginAsBackendCtrl controller = new FieloCMSPLT_LoginAsBackendCtrl();
        system.currentPageReference().getParameters().put('memberId',member.Id); 
        try {
            controller.redirect();
        } catch (Exception e) {
        }
    }
    
}