src/objects/FieloPLT__Agreement__c.object
<CustomObject>
    <description>Terms and conditions of service that Members need to accept in order to be part of the loyalty Program in which you wish to include them.</description>
    <fields>
        <fullName>FieloPLT__Agreement__c</fullName>
        <description>Agreement terms and conditions.</description>
        <inlineHelpText>Enter the Agreement terms and conditions.</inlineHelpText>
        <label>Agreement</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program which the Agreement belongs to.</description>
        <inlineHelpText>Choose Program which the Agreement belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Version</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Agreement.</description>
        <inlineHelpText>Related Agreement.</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>FieloPLT__Agreement__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_AgreementAcceptCtrl.cls
public with sharing class FieloCMSPLT_AgreementAcceptCtrl {

    public Boolean showAgreement {get; set;}
    public FieloPLT__Agreement__c agreement {get; set;}

    public FieloCMSPLT_AgreementAcceptCtrl(){
        //looks for the current agreement and the logged in user
        FieloPLT__Member__c member = new FieloCMSPLT_MembersSelector(new Set<String>{'Id', 'FieloPLT__Agreement__c', 'FieloPLT__Program__c'}).selectById(new Set<Id>{FieloCMSPLT_MemberService.getCurrentMemberId()})[0];
        List<FieloPLT__Agreement__c> agreements = new FieloCMSPLT_AgreementsSelector(new Set<String>{'Id', 'FieloPLT__Agreement__c '}).selectCurrentByProgram(member.FieloPLT__Program__c);
    
        showAgreement = false;
        if(!agreements.isEmpty()){
            //chequeo si el member tiene el último agreement aceptado
            agreement = agreements[0];
            showAgreement = member.FieloPLT__Agreement__c != agreements[0].Id;
        }
    }

    public static PageReference doSave(){
        FieloPLT__Member__c member = new FieloCMSPLT_MembersSelector(new Set<String>{'Id', 'FieloPLT__Agreement__c', 'FieloPLT__Program__c'}).selectById(new Set<Id>{FieloCMSPLT_MemberService.getCurrentMemberId()})[0];
        List<FieloPLT__Agreement__c> agreements = new FieloCMSPLT_AgreementsSelector(new Set<String>{'Id'}).selectCurrentByProgram(member.FieloPLT__Program__c);
        //if the member exists and have accepted the agreement then updates the agreement for the member
        member.FieloPLT__Agreement__c = agreements[0].Id;
        FieloPLT.SObjectService.enableAdminPermission(true);
        try{
            upsert member;
        }catch(DMLException e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Error, e.getDMLMessage(0)));
            return null;                    
        }                

        //if no errors checks then returns to the ret url
        if(!ApexPages.hasMessages()){
            String retUrl = ApexPages.currentPage().getParameters().get('retUrl');
            if(retUrl != null){
                return new PageReference('/' + retUrl);
            }
        }
        return null;
    }
        
}