src/objects/FieloPLT__Agreement__c.object
<CustomObject>
    <description>Terms and conditions of service that Members need to accept in order to be part of the loyalty Program in which you wish to include them.</description>
    <fields>
        <fullName>FieloPLT__Agreement__c</fullName>
        <description>Agreement terms and conditions.</description>
        <inlineHelpText>Enter the Agreement terms and conditions.</inlineHelpText>
        <label>Agreement</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program which the Agreement belongs to.</description>
        <inlineHelpText>Choose Program which the Agreement belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Agreement status: Draft, Current, Active or Deprecated.</description>
        <inlineHelpText>Agreement status. Only one Agreement be active.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Version</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <fields>
        <fullName>SiteDomain__c</fullName>
        <label>Site Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgreementsSelectorTest.cls
@isTest
private class AgreementsSelectorTest{
    @isTest
    static void itShould_1(){
        // Given
        FieloPLT__Program__c program = new FieloPLT__Program__c(Name = 'Test', SiteDomain__c = 'www.fielo.com');
        insert program;
        
        FieloPLT__Agreement__c agreement = new FieloPLT__Agreement__c(
            FieloPLT__Agreement__c = 'test',
            FieloPLT__Program__c = program.Id,
            FieloPLT__Status__c = 'Current'
        );
        insert agreement;
        
        List<FieloPLT__Agreement__c> agreements1 = new AgreementsSelector().selectById(new Set<Id>{agreement.Id});
        List<FieloPLT__Agreement__c> agreements2 = new AgreementsSelector(new Set<String>{'Name'}).selectById(new Set<Id>{agreement.Id});
        List<FieloPLT__Agreement__c> agreements3 = new AgreementsSelector().selectCurrentByProgram(program.Id);
    
    }
}