src/objects/FieloAlpha__Agreement__c.object
<CustomObject>
    <customHelpPage>FieloAlpha__AgreementHelpBackEnd</customHelpPage>
    <fields>
        <fullName>FieloAlpha__Agreement__c</fullName>
        <description>Name of the agreement</description>
        <inlineHelpText>Enter the text of the agreement.</inlineHelpText>
        <label>Agreement</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FieloAlpha__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The program to which this agreement belongs.</description>
        <inlineHelpText>Select the program to which this agreement belongs.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloAlpha__Program__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloAlpha__Status__c</fullName>
        <description>This field allow to follow the lifecycle of an agreement:
Draft: user is writting the next release
Current: As soon as a draft is finish and active, it becomes as Current version, so this is the active one, and each one a member access to the front end or mobile, he has to &quot;check it&quot; as agreed.
Deprecated: Once a new version is Current, previous Current is Deprecated.
Remember that if &quot;Use Agreement&quot; is unchecked for the corresponding program, no agreement will be shown in the front end.</description>
        <inlineHelpText>Set the status for this agreement. You can have only one active agreement per program.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Version</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloAlpha__Member__c.object
<CustomObject>
    <customHelpPage>FieloPLT__MemberHelpBackEnd</customHelpPage>
    <label>Member</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloAlpha__Program__c.object
<CustomObject>
    <description>Settings of each of your Fielo programs. You can create up to XXXX different programs.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgreementAcceptController.cls
public with sharing class AgreementAcceptController {

    public FieloAlpha__Agreement__c agreement {get;set;}
    public Boolean acceptAgreement {get;set;}

    private FieloAlpha__Member__c member;

    public AgreementAcceptController() {
        acceptAgreement = false;
        //looks for the current agreement and the logged in user
        member = [SELECT Id, FieloAlpha__Program__c FROM FieloAlpha__Member__c WHERE Id =: MemberService.getCurrentMemberId()];        
        agreement = [SELECT Id, FieloAlpha__Agreement__c FROM FieloAlpha__Agreement__c WHERE FieloAlpha__Status__c = 'Current' AND FieloAlpha__Program__c =: member.FieloAlpha__Program__c LIMIT 1];
    }

    public PageReference doSave(){
        //if the member exists and have accepted the agreement then updates the agreement for the member
        if(acceptAgreement){
            member.FieloAlpha__Agreement__c = agreement.Id;
            FieloAlpha.OrganizationUtil.validateReadOnlyFieldsMember(false);
            try{
                upsert member;
            }catch(DMLException e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Error, e.getDMLMessage(0)));
                return null;                    
            }                
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.Error, 'You must accept the agreement to continue.'));
            return null;
        }
        
        //if no errors checks then returns to the ret url
        if(!ApexPages.hasMessages()){
            String retUrl = ApexPages.currentPage().getParameters().get('retUrl');
            if(retUrl != null){
                return new PageReference('/' + retUrl);
            }
        }
        return null;
    }
        
}