src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Salesforce CRM Account name.</description>
        <inlineHelpText>Salesforce CRM Account name.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Salesforce CRM Contact.</description>
        <inlineHelpText>Related Salesforce CRM Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Email__c</fullName>
        <description>Member&apos;s email</description>
        <inlineHelpText>Enter Member&apos;s email.</inlineHelpText>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Member is a Manager of the Organization Account.</description>
        <inlineHelpText>Member is a Manager of their Organization Account.</inlineHelpText>
        <label>Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__OrganizationAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organization account linked to the Organization Contributor account.</description>
        <inlineHelpText>Choose Organization account where the Organization Contributor Member belongs to.</inlineHelpText>
        <label>Organization Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Member must be an &quot;Organization Account&quot; and belong to the same Program.</errorMessage>
            <filterItems>
                <field>FieloPLT__Member__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Organization Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Members (Organization Account)</relationshipLabel>
        <relationshipName>FieloAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Status__c</fullName>
        <description>Member&apos;s status.</description>
        <inlineHelpText>Member&apos;s status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FieloPLT__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member&apos;s User.</description>
        <inlineHelpText>Enter the Member&apos;s User.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieloCMSPLT_MembersSelector.cls
public with sharing class FieloCMSPLT_MembersSelector extends FieloCMSPLT_SObjectSelector{

	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField>{
            FieloPLT__Member__c.Id,
			FieloPLT__Member__c.Name,
			FieloPLT__Member__c.FieloPLT__Email__c,
			FieloPLT__Member__c.FieloPLT__Program__c,
			FieloPLT__Member__c.FieloPLT__User__c,
			FieloPLT__Member__c.FieloPLT__Account__c,
			FieloPLT__Member__c.FieloPLT__Status__c,
            FieloPLT__Member__c.FieloPLT__OrganizationAccount__c,
            FieloPLT__Member__c.FieloPLT__Contact__c,
            FieloPLT__Member__c.FieloPLT__IsManager__c
		};
	}

	public FieloCMSPLT_MembersSelector(Set<String> fields){
		super(fields);
	}

	public FieloCMSPLT_MembersSelector(){
		super();
	}

	public Schema.SObjectType getSObjectType(){
		return FieloPLT__Member__c.SObjectType;
	}

	public List<FieloPLT__Member__c> selectById(Set<Id> memberIds){
		return (List<FieloPLT__Member__c>) selectSObjectsById(memberIds);
	}

	public List<FieloPLT__Member__c> selectRelatedMembers(Id userId, Id programId){
		assertIsAccessible();
		String fieldSet = getFieldListString();
		if(!fieldset.contains('OrganizationAccount__c')){
			fieldSet += ',OrganizationAccount__c';
		}
		if(!fieldset.contains('IsManager__c')){
			fieldSet += ',IsManager__c';
		}
		String query = String.format(
				'select {0} ' +
				  'from {1} ' +
				  'where FieloPLT__User__c =: userId AND FieloPLT__Program__c =: programId {2} {3} ',
				new List<String> {
					fieldSet,
					getSObjectName(), getLimitCondition(), getOffsetCondition()});

		List<FieloPLT__Member__c> members = (List<FieloPLT__Member__c>)Database.query(query);

    	return members;
	}

	public List<FieloPLT__Member__c> selectByOrganizationAccount(Id orgAccountId){
		assertIsAccessible();
		String query = String.format(
				'select {0} ' +
				  'from {1} ' +
				  'where FieloPLT__OrganizationAccount__c =: orgAccountId {2} {3}',
				new List<String> {getFieldListString(),getSObjectName(),getLimitCondition(), getOffsetCondition()});

		return (List<FieloPLT__Member__c>) Database.query(query);
	}

}