src/objects/FieloPLT__Member__c.object
<CustomObject>
    <description>Members are the people or entities registered in your Program.</description>
    <fields>
        <fullName>FieloPLT__Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Program where the Member belongs to.</description>
        <inlineHelpText>Program the Member belongs to.</inlineHelpText>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operations settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProgramService.cls
public class ProgramService{
	private static FieloPLT__Program__c currentProgram;
	public static FieloPLT__Program__c getCurrentProgram(){
		if(currentProgram == null){
			Id currentMemberId = MemberService.getCurrentMemberId();
			//si es guest tomo el pr
			if(currentMemberId == null){				
				currentProgram = new ProgramsSelector(false).selectBySiteUrl(Site.getDomain());
			}else{
				Id programId = [SELECT FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Id =: currentMemberId].FieloPLT__Program__c;
				currentProgram = new ProgramsSelector(true).selectById(new Set<Id>{programId}).get(0);
			}
		}
		return currentProgram;
	}

	public static FieloPLT__Program__c getProgramByDomain(){
        return new ProgramsSelector(false).selectBySiteUrl(Site.getDomain());
    }

}